<?php

namespace Database\Seeders;

class ArticleRuteSeeder extends BaseArticleSeeder
{
    public function run(): void
    {
        $this->store([
            [
                'title' => 'Panduan Kirim Barang dari Jawa ke Sumatera: Rute, Ongkir, dan Waktu Tempuh',
                'slug' => 'panduan-kirim-dari-jawa-ke-sumatera-rute-ongkir-waktu-tempuh',
                'category' => 'tips-tutorial',
                'meta_title' => 'Kirim Barang Jawa ke Sumatera: Rute, Ongkir, Waktu | ATL Express',
                'meta_description' => 'Panduan pengiriman dari Jawa ke Sumatera: pilihan moda laut dan udara, estimasi waktu tempuh, tips pengemasan, dan cara cek ongkir online.',
                'days_ago' => 1,
                'hour' => 8,
                'lead' => 'Sumatera termasuk tujuan paling ramai dari pengiriman keluar Jawa. Karena jarak dan kondisi geografisnya, pilihan moda dan persiapan logistik sangat menentukan biaya serta kecepatan barang sampai.',
                'sections' => [
                    ['Dua Rute Utama: Laut dan Udara',
                        'Jalur laut menjadi pilihan paling umum untuk kargo dari Jawa ke Sumatera, terutama barang dalam jumlah banyak. Jalur udara dipilih ketika barang bernilai tinggi, berukuran kecil, dan harus sampai dalam hitungan hari. Keduanya punya pola jadwal yang berbeda, dan pilihan terbaik bergantung pada urgensi serta nilai barang.'],
                    ['Perhitungkan Waktu Tempuh dan Buffer',
                        'Untuk jalur laut, siapkan satu sampai tiga hari untuk perjalanan dan tambahan waktu untuk bongkar muat di dock serta penanganan di kota tujuan. Jalur udara bisa lebih cepat, tetapi ingat bahwa ongkos dihitung berdasarkan berat dan volume, sehingga kemasan yang rapat sangat berpengaruh pada tagihan.'],
                    ['Kota Tujuan yang Sering Dilayani',
                        'Medan, Banda Aceh, Padang, Pekanbaru, Jambi, Palembang, Bandar Lampung, dan Bengkulu menjadi kota yang paling sering menjadi tujuan. Untuk daerah di luar kota-kota tersebut, barang biasanya diteruskan melalui jaringan mitra kami.'],
                ],
                'tips_title' => 'Tips Kirim ke Sumatera',
                'tips' => [
                    'Kemas dengan bubble wrap dan kardus dobel karena bongkar muat di kapal cukup berat.',
                    'Kirim barang lebih awal saat periode harbolnas atau hari raya.',
                    'Tulis label alamat di beberapa sisi kemasan agar mudah dibaca di gudang transit.',
                    'Hitung ongkir di '.self::link('halaman cek tarif', '/cek-tarif').' lalu konfirmasi jadwal keberangkatan ke tim kami.',
                ],
                'ctas' => [
                    ['Tanya jadwal kapal dan ongkir ke Sumatera',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' dan sebutkan kota tujuan, berat, serta volume barang Anda.'],
                ],
            ],
            [
                'title' => 'Pengiriman Jawa ke Sumatera Selatan: Bandar Lampung dan Palembang',
                'slug' => 'pengiriman-jawa-ke-sumatera-selatan-bandar-lampung-palembang',
                'category' => 'berita',
                'meta_title' => 'Cargo Jawa ke Sumatera Selatan: Lampung dan Palembang | ATL Express',
                'meta_description' => 'Pengiriman barang dari Jawa ke Sumatera Selatan lewat Bandar Lampung dan Palembang, lengkap dengan pilihan moda, estimasi waktu, dan tips pengemasan.',
                'days_ago' => 3,
                'hour' => 9,
                'lead' => 'Sumatera Selatan punya dua pintu masuk utama bagi kargo yang datang dari Jawa, yaitu pelabuhan Bandar Lampung di sisi tenggara dan Discharge Point di Muara Enim yang melayani area Palembang. Rute ini termasuk yang paling stabil.',
                'sections' => [
                    ['Bandar Lampung Jadi Titik Transit Utama',
                        'Bandar Lampung menjadi gerbang laut bagi sebagian besar kargo dari Jawa sekaligus titik transit menuju wilayah pesisir Sumatera Selatan. Keberadaan jaringan trucking lokal membuat barang dari dock bisa diteruskan ke kota sekitarnya dengan waktu tambahan yang relatif singkat.'],
                    ['Menuju Palembang dan Sekitarannya',
                        'Setelah tiba di Sumatera Selatan, barang dengan tujuan Palembang diteruskan ke pusat distribusi dalam kota. Untuk pengiriman ke kabupaten seperti Ogan Ilir, Banyuasin, dan Muara Enim, waktu tambahan perlu disampaikan di muka agar pelanggan punya harapan yang sesuai.'],
                    ['Komoditas yang Sering Dikirim',
                        'Produk elektronik kecil, makanan kering, bahan bangunan, sparepart mesin, serta hasil pertanian seperti kopi dan pala banyak dikirim melalui rute ini. Cairan seperti minyak kemasan perlu diperiksa lebih awal karena memerlukan kemasan khusus.'],
                ],
                'tips_title' => 'Yang Perlu Disiapkan untuk Rute Ini',
                'tips' => [
                    'Konsultasikan pilihan kemasan untuk cairan melalui '.self::link('halaman kontak', '/kontak').'.',
                    'Tanyakan apakah pengiriman perlu dipecah menjadi beberapa kali angkut.',
                    'Minta jadwal keberangkatan kapal berikutnya sebelum menyetujui tanggal kirim.',
                    'Pastikan penerima berada di lokasi saat status kiriman masuk tahap akhir.',
                ],
                'ctas' => [
                    ['Hitung ongkir ke Bandar Lampung dan Palembang',
                        'Gunakan '.self::link('cek tarif online', '/cek-tarif').' untuk estimasi biaya, lalu konfirmasi jadwalnya ke tim kami.'],
                ],
            ],
            [
                'title' => 'Cargo Jawa ke Sumatera Utara: Pilih Udara atau Laut ke Medan',
                'slug' => 'cargo-jawa-ke-sumatera-utara-pilih-udara-atau-laut-ke-medan',
                'category' => 'tips-tutorial',
                'meta_title' => 'Kirim Barang ke Medan dan Sumatera Utara | ATL Express',
                'meta_description' => 'Pilihan pengiriman dari Jawa ke Medan dan Sumatera Utara: cargo udara untuk barang kilat, cargo laut untuk volume besar, dan tips memilih moda yang tepat.',
                'days_ago' => 5,
                'hour' => 13,
                'lead' => 'Medan adalah pusat industri dan perdagangan terbesar di Sumatera Utara, sehingga permintaan kiriman dari Jawa cukup tinggi. Karena jarak yang jauh, memilih moda yang tepat akan menghemat biaya yang signifikan.',
                'sections' => [
                    ['Kapan Cargo Udara Layak Dipilih',
                        'Cargo udara menjadi pilihan untuk dokumen, elektronik, masker, komponen mesin, dan barang bernilai tinggi yang tidak boleh lama tertunda. Ongkos udara dihitung berdasarkan berat atau volume, sehingga pengemasan yang rapat sangat berpengaruh pada tagihan akhir.'],
                    ['Kapan Jalur Laut Lebih Menghemat',
                        'Untuk barang dalam jumlah besar seperti bahan bangunan, makanan dalam jumlah besar, atau hasil bumi, jalur laut jauh lebih ekonomis. Waktu tunggunya perlu direncanakan sejak awal agar tidak menghambat proses penjualan.'],
                    ['Pertimbangan Khusus di Wilayah Utara',
                        'Kondisi akses daratan di sekitar kota Sumatera Utara membuat distribusi membutuhkan perencanaan yang baik. Karena itu, data alamat yang lengkap sampai tingkat kecamatan sangat membantu, dan kami memusatkan perhatian pada hal ini di setiap tahap pengemasan dan transit.'],
                ],
                'tips_title' => 'Tips Efisiensi Kirim ke Medan',
                'tips' => [
                    'Padatkan kemasan agar volume tidak membengkak dan biaya udara tetap terkendali.',
                    'Kirim barang rapuh dengan bubble wrap ganda dan pelindung sudut.',
                    'Pastikan nama dan nomor telepon penerima sudah benar pada formulir.',
                    'Pantau status kiriman lewat '.self::link('cek resi online', '/cek-resi').'.',
                ],
                'ctas' => [
                    ['Bandingkan biaya udara dan laut',
                        'Sampaikan detail paket ke '.self::link('tim kami', '/kontak').' agar kami bisa membantu menghitung opsi paling hemat.'],
                ],
            ],
            [
                'title' => 'Pengiriman ke Sumatera Barat, Bengkulu, dan Sekitarannya',
                'slug' => 'pengiriman-ke-sumatera-barat-bengkulu-dan-sekitarnya',
                'category' => 'berita',
                'meta_title' => 'Kirim Barang ke Sumatera Barat dan Bengkulu | ATL Express',
                'meta_description' => 'Jasa pengiriman dari Jawa ke Sumatera Barat, Bengkulu, dan wilayah sekitarnya, lengkap dengan informasi rute, moda pengiriman, dan tips agar barang tepat waktu.',
                'days_ago' => 7,
                'hour' => 10,
                'lead' => 'Padang sebagai ibu kota Sumatera Barat dan Bengkulu sebagai gerbang ke wilayah Bengkulu menjadi tujuan yang perlu perencanaan khusus. Rute ini memakan waktu lebih panjang, tetapi biayanya bisa lebih hemat bila dikirim bersama kargo lain.',
                'sections' => [
                    ['Tentang Jalur ke Padang',
                        'Kargo dari Jawa menuju Padang umumnya dikombinasikan dengan jalur laut menuju pelabuhan utama, lalu dilanjutkan dengan trucking darat. Jadwal pelayaran menentukan kapan barang masuk tahap akhir, sehingga pengiriman yang dijadwalkan rutin perlu disusun lebih awal.'],
                    ['Bengkulu dan Sekitarannya',
                        'Bengkulu berada di ujung barat dengan akses yang bergantung pada kondisi jalan. Pengiriman yang memerlukan bongkar muat tambahan perlu disampaikan sejak awal agar estimasi waktu tidak meleset jauh dari kenyataan.'],
                    ['Materi yang Perlu Disiapkan',
                        'Untuk area dengan jaringan yang lebih terbatas, pengemasan yang lebih kuat dan label yang jelas menjadi sangat penting. Menyertakan nomor WhatsApp penerima membantu tim kami melakukan koordinasi saat barang tiba di kota tujuan.'],
                ],
                'tips_title' => 'Tips untuk Rute Terjauh',
                'tips' => [
                    'Kirim beberapa hari lebih awal dari batas waktu yang dijanjikan ke pelanggan.',
                    'Pilih layanan dengan tracking agar status kiriman bisa dipantau.',
                    'Siapkan daftar isi barang untuk keperluan klaim.',
                    'Konfirmasi ongkir dan jadwal lewat '.self::link('halaman cek tarif', '/cek-tarif').'.',
                ],
                'ctas' => [
                    ['Rencanakan pengiriman ke Sumatera Barat',
                        'Hubungi tim kami lewat '.self::link('form kontak', '/kontak').' untuk jadwal dan estimasi ongkir terbaru.'],
                ],
            ],
            [
                'title' => 'Kirim Barang ke Riau, Jambi, dan Kepulauan Bangka Belitung',
                'slug' => 'kirim-barang-ke-riau-jambi-dan-kepulauan-bangka-belitung',
                'category' => 'berita',
                'meta_title' => 'Jasa Kirim ke Riau, Jambi, dan Bangka Belitung | ATL Express',
                'meta_description' => 'Pengiriman barang dari Jawa ke Pekanbaru, Jambi, dan Bangka Belitung melalui jalur laut dan udara, dengan fokus pada keandalan, harga, dan transparansi ongkir.',
                'days_ago' => 9,
                'hour' => 11,
                'lead' => 'Riau, Jambi, dan Bangka Belitung punya karakter pengiriman yang mirip: sebagian besar barang datang melalui jalur laut, sementara sebagian kecil memilih udara untuk kebutuhan yang mendesak.',
                'sections' => [
                    ['Pekanbaru dan Sekitarannya',
                        'Pekanbaru menjadi simpul distribusi bagi Riau dan beberapa kabupaten sekitarnya. Barang dari Jawa biasanya tiba di pelabuhan utama, lalu diteruskan ke kota-kota dalam provinsi melalui jaringan trucking mitra kami.'],
                    ['Jambi dan Tanjung Jabung',
                        'Untuk pengiriman menuju Jambi, pilihan moda dapat disesuaikan dengan urgensi dan volume barang. Kebutuhan industri lokal, mesin peralatan, dan perlengkapan kerja termasuk kategori yang paling sering dikirim ke wilayah ini.'],
                    ['Bangka Belitung dan Jaraknya',
                        'Kepulauan Bangka Belitung berada pada jalur yang relatif jauh dari Jawa, sehingga waktu pengiriman perlu disampaikan dengan jelas sejak awal. Proses pemeriksaan di titik pemrosesan perlu diperhitungkan agar jadwal tidak meleset.'],
                ],
                'tips_title' => 'Yang Perlu Diperhatikan',
                'tips' => [
                    'Konfirmasi jadwal operasional tim mitra di daerah tujuan sebelum kirim.',
                    'Pilih pengemasan yang mampu menahan kelembapan tinggi.',
                    'Simpan nomor resi dan pantau perjalanan lewat '.self::link('cek resi', '/cek-resi').'.',
                    'Minta penawaran tertulis untuk pengiriman rutin bulanan.',
                ],
                'ctas' => [
                    ['Dapatkan jadwal pengiriman ke wilayah ini',
                        'Tanyakan langsung ke '.self::link('tim ATL Express', '/kontak').' dan sebutkan kota tujuan serta ritme pengiriman Anda.'],
                ],
            ],
            [
                'title' => 'Panduan Pengiriman Barang dari Jawa ke Kalimantan',
                'slug' => 'panduan-pengiriman-barang-dari-jawa-ke-kalimantan',
                'category' => 'tips-tutorial',
                'meta_title' => 'Panduan Kirim Barang Jawa ke Kalimantan | ATL Express',
                'meta_description' => 'Cara mengirim barang dari Jawa ke Kalimantan: pilihan moda laut dan udara, tips pengemasan, daftar kota tujuan, dan cara cek ongkir sebelum kirim.',
                'days_ago' => 11,
                'hour' => 10,
                'lead' => 'Kalimantan adalah wilayah luas dengan kondisi akses yang berbeda-beda antar provinsi. Perencanaan pengiriman ke Kalimantan perlu mempertimbangkan moda, jadwal, dan kemungkinan biaya tambahan di daerah tujuan.',
                'sections' => [
                    ['Rute Masuk ke Kalimantan',
                        'Jalur laut masuk melalui Pontianak untuk Kalimantan Barat, Balikpapan untuk Kalimantan Timur, Banjarmasin untuk Kalimantan Selatan, dan Palangka Raya untuk Kalimantan Tengah. Barang kemudian diteruskan ke ibu kota dan kabupaten di sekitarnya.'],
                    ['Kapan Memilih Cargo Udara',
                        'Cargo udara layak dipertimbangkan untuk dokumen, elektronik, masker, dan peralatan medis yang butuh cepat sampai. Untuk volume besar, jalur laut hampir selalu lebih hemat, dan perbedaan biayanya bisa sangat signifikan.'],
                    ['Barang yang Perlu Perhatian khusus',
                        'Barang berbahaya, cairan, bahan kimia, dan tanaman hidup memiliki aturan khusus. Konsultasikan jenis barang Anda kepada tim kami sebelum pengemasan supaya tidak ada kendala di kemudian hari.'],
                ],
                'tips_title' => 'Checklist Kirim ke Kalimantan',
                'tips' => [
                    'Tanyakan jadwal kapal mingguan yang dilayani rute tujuan Anda.',
                    'Gunakan kemasan tahan lembap dengan kekuatan yang memadai.',
                    'Sertakan nomor WhatsApp penerima untuk koordinasi pengambilan.',
                    'Hitung ongkir di '.self::link('halaman cek tarif', '/cek-tarif').' lalu pilih layanan yang sesuai.',
                ],
                'ctas' => [
                    ['Konsultasi rute Kalimantan',
                        'Tim kami siap membantu lewat '.self::link('halaman kontak', '/kontak').', termasuk pilihan moda dan jadwal keberangkatan.'],
                ],
            ],
            [
                'title' => 'Cargo ke IKN Nusantara: Persiapan Logistik Proyek',
                'slug' => 'cargo-ke-ikn-nusantara-persiapan-logistik-proyek',
                'category' => 'berita',
                'meta_title' => 'Jasa Cargo ke IKN Nusantara | ATL Express',
                'meta_description' => 'Pengiriman barang ke IKN Nusantara: kebutuhan logistik pembangunan, pilihan moda pengiriman, dan tips pengemasan untuk material proyek.',
                'days_ago' => 13,
                'hour' => 14,
                'lead' => 'Pembangunan Ibu Kota Nusantara menuntut banyak kebutuhan logistik: material bangunan, alat berat, mesin, perlengkapan kantor, hingga kebutuhan pekerja. Semua itu butuh pengiriman yang direncanakan dengan baik.',
                'sections' => [
                    ['Kebutuhan Logistik yang Tersedia',
                        'Kategori barang yang paling banyak dikirim ke kawasan IKN meliputi material bangunan, sparepart alat berat, genset, kabel, pipa, serta perlengkapan kantor. Setiap kategori punya syarat penanganan berbeda, dari ringan sampai yang memerlukan alat khusus.'],
                    ['Rute Pengiriman ke IKN',
                        'Barang dari Jawa umumnya dikirim ke Kalimantan Timur terlebih dahulu, kemudian diteruskan ke kawasan IKN melalui jaringan darat dan sungai. Untuk barang yang sensitif waktu, jalur udara ke Balikpapan bisa menjadi tahap pertama yang lebih cepat.'],
                    ['Persiapan yang Wajib Dilakukan',
                        'Pastikan dokumen pengiriman lengkap, pengemasan sesuai standar, dan ada koordinator lapangan yang paham jadwal penerimaan di lokasi proyek. Tim kami membantu mengoordinasikan jadwal agar material tidak menumpuk di gudang.'],
                ],
                'tips_title' => 'Tips Logistik Proyek ke IKN',
                'tips' => [
                    'Kirim material terjadwal agar biaya transport lebih hemat.',
                    'Gunakan label nama proyek dan lokasi unloading yang jelas.',
                    'Siapkan kontak penerima di lokasi untuk proses bongkar muat.',
                    'Minta penawaran dan jadwal melalui '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Rencanakan pengiriman material ke IKN',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk konsultasi rute, moda, dan jadwal penerimaan di lokasi proyek.'],
                ],
            ],
            [
                'title' => 'Pengiriman ke Sulawesi: Makassar dan Manado',
                'slug' => 'pengiriman-ke-sulawesi-makassar-dan-manado',
                'category' => 'berita',
                'meta_title' => 'Jasa Kirim ke Sulawesi: Makassar dan Manado | ATL Express',
                'meta_description' => 'Pengiriman barang dari Jawa ke Makassar, Manado, dan wilayah Sulawesi lainnya, lengkap dengan panduan moda pengiriman, tips pengemasan, dan estimasi waktu tiba.',
                'days_ago' => 15,
                'hour' => 9,
                'lead' => 'Sulawesi punya bentuk pulau yang unik dengan jaringan jalan yang tidak selaluhubungan langsung antar kota. Pengiriman ke Makassar dan Manado menjadi dua tujuan yang paling banyak dicari, masing-masing dengan karakter rute berbeda.',
                'sections' => [
                    ['Makassar sebagai Pintu Masuk',
                        'Makassar menjadi simpul terbesar di Sulawesi Selatan dan pusat distribusi bagi wilayah timur. Barang dari Jawa umumnya tiba melalui jalur laut, lalu diteruskan ke kota-kota seperti Parepare, Palu, dan Mamuju.'],
                    ['Manado dan Sekitarannya',
                        'Untuk pengiriman ke Manado, jalur laut memerlukan waktu lebih lama sehingga jalur udara sering dipilih untuk kebutuhan yang sensitif waktu. Mesin, obat, dan dokumen termasuk kategori yang paling umum dikirim dengan cara udara.'],
                    ['Cuaca dan Kondisi Jalan',
                        'Cuaca di beberapa wilayah Sulawesi bisa memengaruhi jadwal keberangkatan dan kondisi jalan. Karena itu, tim kami menginformasikan rencana pengiriman dan perubahan jadwal secara proaktif agar pengirim bisa memberi tahu pelanggan.'],
                ],
                'tips_title' => 'Tips Menuju Sulawesi',
                'tips' => [
                    'Pilih moda berdasarkan urgensi dan nilai barang, bukan sekadar ongkir.',
                    'Gunakan kemasan kuat untuk perjalanan yang melibatkan banyak perpindahan.',
                    'Pantau status kiriman melalui '.self::link('cek resi', '/cek-resi').' secara berkala.',
                    'Diskusikan jadwal sebelum hari besar yang expectant mengganggu operasional mitra.',
                ],
                'ctas' => [
                    ['Tanyakan opsi ke Makassar dan Manado',
                        'Hubungi '.self::link('tim kami', '/kontak').' dan jelaskan kebutuhan Anda agar kami bisa menyusun rencana pengiriman terbaik.'],
                ],
            ],
            [
                'title' => 'Cargo ke Bali, Lombok, dan Nusa Tenggara',
                'slug' => 'cargo-ke-bali-lombok-dan-nusa-tenggara',
                'category' => 'tips-tutorial',
                'meta_title' => 'Jasa Cargo ke Bali, Lombok, dan Nusa Tenggara | ATL Express',
                'meta_description' => 'Pengiriman barang dari Jawa ke Bali, Lombok, Sumbawa, Flores, dan Nusa Tenggara Timur, lengkap dengan pilihan moda, tips pengemasan, dan catatan jadwal.',
                'days_ago' => 17,
                'hour' => 15,
                'lead' => 'Pengiriman ke Bali dan Nusa Tenggara relatif lebih mudah karena jalur Jawa menuju Bali sudah matang. Untuk wilayah lebih timur seperti Flores dan Timor, penyesuaian jadwal dan biaya tambahan perlu diperhitungkan.',
                'sections' => [
                    ['Bali: Jalur yang Sudah Matang',
                        'Rute Jawa ke Bali dilayani armada darat dan kapal feri dengan jadwal yang relatif sering. Karena kelancaran jalur ini, biaya pengiriman ke Bali cenderung lebih stabil dan mudah diprediksi dibandingkan tujuan di luar jalur tersebut.'],
                    ['Lombok dan Nusa Tenggara Barat',
                        'Lombok, Sumbawa, dan pulau-pula kecil di sekitarnya dilayani melalui jaringan penghantaran yang terhubung ke Bali. Barang dalam jumlah besar yang ditahan di Bali bisa diteruskan ke Lombok setelah tiba.'],
                    ['Menuju Timur: Flores dan Timor',
                        'Wilayah Nusa Tenggara Timur memiliki jarak yang jauh dan jaringan pengiriman yang lebih terbatas. Rute ini perlu direncanakan dengan cermat, terutama untuk barang bernilai tinggi yang tidak boleh terlalu lama dalam perjalanan.'],
                ],
                'tips_title' => 'Tips Kirim ke Bali dan Nusa Tenggara',
                'tips' => [
                    'Manfaatkan jadwal kapal yang sering untuk memangkas waktu tunggu.',
                    'Kemas barang yang mudah rusak dengan bubble wrap dan kardus dobel.',
                    'Lengkapi alamat penerima sampai tingkat jalan dan nomor rumah.',
                    'Cek ongkir di '.self::link('halaman cek tarif', '/cek-tarif').' sebelum barang dikemas.',
                ],
                'ctas' => [
                    ['Rencanakan pengiriman ke Bali dan Nusa Tenggara',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk jadwal keberangkatan dan estimasi biaya.'],
                ],
            ],
            [
                'title' => 'Pengiriman ke Maluku dan Papua: Jangka Waktu Terpanjang',
                'slug' => 'pengiriman-ke-maluku-dan-papua',
                'category' => 'berita',
                'meta_title' => 'Jasa Kirim ke Maluku dan Papua | ATL Express',
                'meta_description' => 'Pengiriman barang dari Jawa ke Ambon, Ternate, Sorong, Jayapura, dan Merauke, lengkap dengan tips memilih moda, pengemasan, dan perkiraan waktu tempuh.',
                'days_ago' => 19,
                'hour' => 10,
                'lead' => 'Maluku dan Papua adalah wilayah paling timur Indonesia dengan jarak tempuh terpanjang dari Jawa. Pengiriman ke kedua wilayah ini menuntut perencanaan khusus, baik dari sisi moda, jadwal, maupun anggaran.',
                'sections' => [
                    ['Maluku: Ambon dan Sekitarannya',
                        'Ambon menjadi pusat layanan untuk Maluku, dan sebagian besar kargo dari Jawa tiba melalui jalur laut dengan transit di Makassar. Barang kemudian dibagikan ke kota seperti Tual, Saumlaki, dan Seram melalui jaringan mitra.'],
                    ['Papua: Dua Jalur dengan Karakter Berbeda',
                        'Bagian barat Papua seperti Fakfak, Sorong, dan Manokwari umumnya dilayani melalui jalur laut dari Sulawesi. Pengiriman ke tujuan seperti Jayapura dan Merauke memerlukan pengaturan jadwal agar waktu tempuh tetap masuk akal bagi penerima.'],
                    ['Apa yang Perlu Disiapkan',
                        'Karena waktu tempuh yang panjang, pengemasan menjadi lapisan perlindungan utama. Barang yang rentan rusak akibat kelembapan perlu kemasan tambahan, dan dokumen pengiriman sebaiknya disalin dalam dua rangkap.'],
                ],
                'tips_title' => 'Tips Kirim ke Timur',
                'tips' => [
                    'Kirim lebih awal dari tenggat waktu karena tempuhannya lebih lama.',
                    'Gunakan kemasan tahan lembap dan label yang tidak mudah basah.',
                    'Minta status kiriman secara berkala lewat '.self::link('cek resi', '/cek-resi').'.',
                    'Pertimbangkan asuransi untuk barang bernilai tinggi.',
                ],
                'ctas' => [
                    ['Konsultasi pengiriman ke Maluku dan Papua',
                        'Sampaikan detail barang ke '.self::link('tim kami', '/kontak').' agar kami bisa menghitung opsi moda dan waktunya.'],
                ],
            ],
            [
                'title' => 'Kirim dari Sumatera ke Jawa: Rute Balik yang Sering Dilupakan',
                'slug' => 'kirim-dari-sumatera-ke-jawa-rute-balik',
                'category' => 'tips-tutorial',
                'meta_title' => 'Kirim Barang dari Sumatera ke Jawa: Rute dan Ongkosnya',
                'meta_description' => 'Panduan kirim barang dari Sumatera ke Jawa: pilihan moda pengiriman, tips memilih cargo, penghematan ongkir, dan contoh rute yang dipakai UMKM.',
                'days_ago' => 21,
                'hour' => 12,
                'lead' => 'Tidak sedikit pengiriman dari Sumatera ke Jawa yang hanya dianggap remeh oleh pengirim baru. Padahal rute ini punya karakteristik dan kebutuhan yang berbeda dari pengiriman keluar Jawa.',
                'sections' => [
                    ['Kenapa Rute Balik Perlu Diperhatikan',
                        'Kargo dari Sumatera ke Jawa sering berupa hasil bumi, produk olahan, dan bahan mentah yang perlu dikirim dalam kondisi baik. Karena itu, kualitas kemasan dan kecepatan penanganan menjadi hal yang lebih penting.'],
                    ['Moda yang Cocok untuk Rute Balik',
                        'Untuk hasil bumi dalam jumlah besar, jalur laut adalah pilihan utama. Untuk barang bernilai tinggi seperti hasil pertanian dan olahan rempah, jalur udara dapat dipilih agar mutu dan nilai barang tetap terjaga.'],
                    ['Tips agar Ongkos Tetap Irit',
                        'Menggabungkan beberapa pengiriman menjadi satu jadwal yang sama sering menurunkan ongkir per kilogram. Pengiriman rutin dengan jadwal tetap juga membantu kami merencanakan keberangkatan kapal dan jaringan yang sama.'],
                ],
                'tips_title' => 'Tips Pengiriman Balik',
                'tips' => [
                    'Kemasan harus mampu menahan perjalanan panjang tanpa kebocoran.',
                    'Pastikan barang tidak memerlukan izin khusus yang belum diurus.',
                    'Minta ongkir di '.self::link('halaman cek tarif', '/cek-tarif').' lalu bandingkan dengan pilihan moda lain.',
                    'Simpan bukti pengiriman untuk keperluan klaim.',
                ],
                'ctas' => [
                    ['Hitung ongkir dari Sumatera ke Jawa',
                        'Buka '.self::link('halaman cek tarif', '/cek-tarif').' atau hubungi '.self::link('tim kami', '/kontak').' untuk konsultasi.'],
                ],
            ],
            [
                'title' => 'Jadwal Pelayaran Cargo Laut: Kapan Barang Bisa Naik Kapal',
                'slug' => 'jadwal-pelayaran-cargo-laut-kapan-barang-bisa-naik-kapal',
                'category' => 'tips-tutorial',
                'meta_title' => 'Jadwal Pelayaran Cargo Laut dan Waktu Muat | ATL Express',
                'meta_description' => 'Memahami jadwal pelayaran, waktu muat, dan proses bongkar muat pada pengiriman cargo laut, serta tips mengatur waktu kirim agar barang tidak menumpuk.',
                'days_ago' => 23,
                'hour' => 8,
                'lead' => 'Banyak keluhan tentang pengiriman laut berawal dari ekspektasi jadwal yang tidak realistis. Barang tidak langsung naik kapal setelah dijemput: ada proses sortir, pengemasan, penempatan di dock, lalu menunggu jadwal keberangkatan.',
                'sections' => [
                    ['Tahapan Barang dari Gudang sampai Kapal',
                        'Setelah barang diterima, tim kami melakukan penimbangan ulang, pengemasan, dan pelabelan. Selanjutnya barang masuk antrean di dock sebelum dimuat ke kapal sesuai jadwal yang tersedia untuk rute tersebut.'],
                    ['Kenapa Jadwal Bisa Berubah',
                        'Cuaca buruk, kondisi pelabuhan, dan menumpuknya muatan bisa memengaruhi jadwal keberangkatan. Karena itu, kami menginformasikan perubahan rencana kepada pengirim agar pelanggan dapat diberi tahu lebih awal.'],
                    ['Cara Merencanakan Waktu Kirim',
                        'Kerjakan mundur dari tenggat waktu penerima. Jika barang harus sampai pada tanggal tertentu, tambahkan waktu cadangan di kedua ujung, yaitu di tempat asal dan di kota tujuan.'],
                ],
                'tips_title' => 'Tips Menjadwalkan Kiriman',
                'tips' => [
                    'Kirim barang beberapa hari lebih awal dari kebutuhan pelanggan.',
                    'Tanyakan jadwal keberangkatan berikutnya sebelum menyetujui tanggal.',
                    'Ikuti pembaruan status lewat '.self::link('cek resi online', '/cek-resi').'.',
                    'Hubungi CS bila jadwal berubah agar informasi cepat sampai ke pelanggan.',
                ],
                'ctas' => [
                    ['Tanyakan jadwal keberangkatan terbaru',
                        'Tim kami di '.self::link('halaman kontak', '/kontak').' bisa membantu menyusun jadwal kirim yang paling aman untuk tenggat Anda.'],
                ],
            ],
            [
                'title' => 'Dokumen Legalitas dan Bea Masuk untuk Cargo Lintas Pulau',
                'slug' => 'dokumen-legalitas-dan-bea-masuk-untuk-cargo-lintas-pulau',
                'category' => 'tips-tutorial',
                'meta_title' => 'Dokumen Legalitas Cargo Lintas Pulau dan Bea Masuk',
                'meta_description' => 'Panduan dokumen pengiriman cargo lintas pulau: invoice, NPWP, izin operasional, aturan barang terbatas, dan perhitungan bea masuk untuk barang dari luar negeri.',
                'days_ago' => 25,
                'hour' => 11,
                'lead' => 'Banyak pengiriman tertunda bukan karena ongkir, melainkan karena dokumen yang tidak lengkap. Mengetahui dokumen dasar sejak awal mempercepat proses dan menghindari biaya tambahan di tengah perjalanan.',
                'sections' => [
                    ['Dokumen Dasar Pengiriman',
                        'Untuk pengiriman niaga dalam negeri, siapkan invoice atau surat jalan, NPWP atau NIK sesuai kebutuhan, serta identitas penerima. Untuk barang kirim, berita acara serah terima juga berguna sebagai bukti barang diterima dalam kondisi baik.'],
                    ['Bea Masuk untuk Barang dari Luar Negeri',
                        'Pengiriman barang yang berasal dari luar negeri melalui bea masuk dan pungutan resmi pabean. Nilai bea masuk dihitung berdasarkan nilai CIF barang, sedangkan pungutan hak cipta dan bea meterai mengikuti ketentuan yang berlaku.'],
                    ['Barang dengan Aturan Khusus',
                        'Barang berbahaya, senjata, obat resep, produk bertanda, dan bahan kimia memerlukan izin atau keterangan tambahan. Konsultasikan jenis barang Anda kepada tim kami sebelum pengemasan.'],
                ],
                'tips_title' => 'Checklist Dokumen',
                'tips' => [
                    'Simpan salinan invoice dan dokumen identitas pengirim serta penerima.',
                    'Pastikan NPWP atau NIK sesuai dengan jenis pengiriman.',
                    'Tanyakan aturan bea masuk bila barang berasal dari luar negeri.',
                    'Konsultasikan barang khusus melalui '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Butuh bantuan pengecekan dokumen?',
                        'Tim kami siap membantu di '.self::link('halaman kontak', '/kontak').' sebelum barang dikirim ke alamat tujuan.'],
                ],
            ],
        ]);
    }
}
