<?php

namespace Database\Seeders;

class ArticleUsahaSeeder extends BaseArticleSeeder
{
    public function run(): void
    {
        $this->store([
            [
                'title' => 'Solusi Logistik untuk UMKM yang Jualan Online',
                'slug' => 'solusi-logistik-untuk-umkm-yang-jualan-online',
                'category' => 'kabar-perusahaan',
                'meta_title' => 'Solusi Logistik untuk UMKM Jualan Online | ATL Express',
                'meta_description' => 'ATL Express bantu UMKM jualan online: ongkir transparan, tracking real-time, door-to-door, dan layanan kirim untuk seluruh Indonesia.',
                'days_ago' => 2,
                'hour' => 14,
                'lead' => 'Untuk UMKM, logistik bukan urusan sampingan. Cara pengiriman menentukan margin, tingkat keluhan, dan apakah pembeli akan membeli lagi. Kabar baiknya, banyak hal bisa disederhanakan dengan sistem yang benar.',
                'sections' => [
                    ['Ongkir yang Terlihat Membantu Menentukan Harga Jual',
                        'Ketika ongkir bisa dihitung sebelum barang dikirim, pemilik usaha bisa menentukan harga jual yang sehat tanpa takut kehilangan. '.self::link('Kalkulator ongkir', '/cek-tarif').' memperlihatkan estimasi biaya sejak awal sehingga kalkulasi margin jadi lebih akurat.'],
                    ['Tracking Mengurangi Keluhan',
                        'Pembeli sering menanyakan status kiriman, dan pertanyaan berulang ini membuang waktu tim admin. Nomor resi yang bisa dilacak mandiri melalui '.self::link('layanan cek resi', '/cek-resi').' membuat komunikasi menjadi jauh lebih efektif.'],
                    ['Door-to-Door untuk Waktu yang Terbatas',
                        'Pemilik usaha yang tinggal di luar kota sudah tidak perlu lagi datang ke kantor cabang. Tim kami bisa menjemput barang langsung di lokasi usaha pada jadwal yang disepakati.'],
                ],
                'tips_title' => 'Alur Kerja untuk UMKM',
                'tips' => [
                    'Siapkan satu kontak khusus untuk semua pengiriman.',
                    'Catat ongkir rata-rata per tujuan setiap bulan.',
                    'Gunakan label dengan logo toko untuk kesan lebih profesional.',
                    'Simpan laporan status kiriman sebagai bahan evaluasi.',
                ],
                'ctas' => [
                    ['Mulai kirim produk UMKM Anda',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' untuk menyusun layanan yang sesuai dengan pola usaha Anda.'],
                ],
            ],
            [
                'title' => 'Kirim Barang dari Marketplace dengan Ongkir yang Jelas',
                'slug' => 'kirim-barang-dari-marketplace-dengan-ongkir-yang-jelas',
                'category' => 'tips-tutorial',
                'meta_title' => 'Kirim Barang Marketplace dengan Ongkir yang Jelas',
                'meta_description' => 'Cara mengirim barang untuk penjualan di marketplace: hitung ongkir online, pilih layanan, dan bagikan tracking agar pembeli tidak menanyakan status kiriman.',
                'days_ago' => 5,
                'hour' => 10,
                'lead' => 'Menjual di marketplace berarti menanggung ongkir yang menjadi bagian dari keputusan pembeli. Ongkos yang bisa dihitung sejak awal membantu Anda menentukan harga yang masih masuk akal dan bisa diterima pembeli.',
                'sections' => [
                    ['Hitung Ongkir Sebelum Menentukan Harga',
                        'Gunakan '.self::link('cek tarif online', '/cek-tarif').' untuk melihat biaya ke kota tujuan sebelum menetapkan harga jual. Dengan begitu, Anda tahu margin setiap produk tanpa harus menebak.'],
                    ['Pilih Layanan yang Sesuai dengan Janji',
                        'Jangan menjanjikan gratis ongkir jika biayanya membuat margin hilang. Tentukan dulu layanan yang realistis, lalu informasikan estimasi waktu kepada pembeli agar ekspektasi mereka sesuai.'],
                    ['Kirim dengan Tracking dan Beri Tau Pembeli',
                        'Kirim nomor resi kepada pembeli segera setelah paket diserahkan. Pembeli yang bisa memantau kiriman sendiri cenderung lebih sabar dan lebih jarang mengirim pesan yang berulang.'],
                ],
                'tips_title' => 'Tips Jualan di Marketplace',
                'tips' => [
                    'Gunakan berat dan volume yang jujur agar ongkir sesuai kenyataan.',
                    'Tetapkan kebijakan pengiriman untuk wilayah jauh di deskripsi produk.',
                    'Kemas dengan rapi karena kondisi barang memengaruhi penilaian pembeli.',
                    'Beri tahu nomor resi lewat '.self::link('cek resi', '/cek-resi').' yang bisa dibuka pembeli.',
                ],
                'ctas' => [
                    ['Tanyakan ongkir ke kota tujuan',
                        'Gunakan '.self::link('halaman cek tarif', '/cek-tarif').' atau hubungi '.self::link('tim kami', '/kontak').' untuk menghitung ongkir toko online Anda.'],
                ],
            ],
            [
                'title' => 'Dropshipping: Kirim Barang Tanpa Perlu Menyimpan Stok',
                'slug' => 'dropshipping-kirim-barang-tanpa-perlu-menyimpan-stok',
                'category' => 'tips-tutorial',
                'meta_title' => 'Dropshipping: Kirim Barang Tanpa Menyimpan Stok',
                'meta_description' => 'Panduan dropshipping untuk pengiriman barang dari pemasok langsung ke pembeli, termasuk Tips cek kualitas, kemasan, dan waktu pengiriman.',
                'days_ago' => 8,
                'hour' => 11,
                'lead' => 'Dropshipping memang menghemat stok, tetapi bukan menghilangkan tanggung jawab atas pengiriman. Justru di sinilah kualitas layanan kirim menentukan apakah pembeli percaya pada toko Anda.',
                'sections' => [
                    ['Kirim Langsung dari Pemasok',
                        'Model ini menghemat modal dan ruang penyimpanan. Yang perlu diperhatikan adalah kejelasan jadwal pengiriman, kondisi kemasan, dan kemampuan pemasok untuk menerbitkan nomor resi bagi pembeli.'],
                    ['Kualitas Kemasan Tetap Penting',
                        'Pembeli menilai pengalaman hanya dari paket yang diterima. Pastikan pengemasan rapi, label alamat benar, dan isi paket sesuai deskripsi produk agar pembeli mau membeli ulang.'],
                    ['Atur Ekspektasi Waktu dengan Jelas',
                        'Sampaikan estimasi waktu pengiriman sejak awal, lalu beri pembaruan status secara berkala. Transaksi yang lancar butuh sedikit komunikasi, bukan banyak.'],
                ],
                'tips_title' => 'Tips Dropshipping',
                'tips' => [
                    'Pastikan pemasok bisa menerima penjemputan sesuai jadwal.',
                    'Gunakan layanan dengan tracking untuk menjaga transparansi.',
                    'Simpan data pembeli untuk pengumuman pengiriman berikutnya.',
                    'Evaluasi kualitas kiriman secara berkala lewat '.self::link('cek resi', '/cek-resi').'.',
                ],
                'ctas' => [
                    ['Bantu supplier kirim ke pembeli Anda',
                        'Tim kami siap menjemput langsung dari pemasok. Hubungi kami lewat '.self::link('halaman kontak', '/kontak').'.'],
                ],
            ],
            [
                'title' => 'Persiapan Ekspor Barang ke Malaysia dan Singapura',
                'slug' => 'persiapan-ekspor-barang-ke-malaysia-dan-singapura',
                'category' => 'tips-tutorial',
                'meta_title' => 'Ekspor Barang ke Malaysia dan Singapura: Persiapan Logistik',
                'meta_description' => 'Panduan pengiriman ekspor dari Jawa ke Malaysia dan Singapura, termasuk dokumen bea masuk, pengemasan, dan pemilihan layanan kargo internasional.',
                'days_ago' => 11,
                'hour' => 9,
                'lead' => 'Ekspor ke negara tetangga punya peluang besar karena jaraknya lebih dekat dan kebiasaan penduduknya relatif mirip. Karena itu, banyak eksportir baru bisa memulai dengan modal kecil.',
                'sections' => [
                    ['Dokumen dan Ketentuan',
                        'Setiap pengiriman ekspor memerlukan dokumen dagang dan bea masuk yang lengkap. Pastikan NPWP, invoice, dan keterangan barang sesuai aturan, karena ketidaksesuaian kecil bisa menambah waktu pemrosesan.'],
                    ['Pengemasan untuk Perjalanan Jauh',
                        'Barang untuk ekspor melewati beberapa tahap dan kemungkinan dipindahkan beberapa kali. Gunakan kemasan yang kokoh, sertakan penanda arah, dan cantumkan kontak yang bisa dihubungi bila terjadi masalah.'],
                    ['Pilih Moda Pengiriman',
                        'Untuk barang dengan nilai tinggi dan volume kecil, udara menjadi pilihan umum. Untuk volume besar, jalur laut jauh lebih ekonomis meski waktunya lebih panjang. Hitung ongkir per kilogram untuk menentukan pilihan terbaik.'],
                ],
                'tips_title' => 'Checklist Sebelum Ekspor',
                'tips' => [
                    'Siapkan dokumen dagang dan bea masuk sejak awal.',
                    'Kemas dengan standar yang lebih kuat untuk perjalanan jauh.',
                    'Tanyakan jadwal dan biaya ekspor ke '.self::link('halaman kontak', '/kontak').'.',
                    'Simpan salinan dokumen pengiriman untuk keperluan administratif.',
                ],
                'ctas' => [
                    ['Tanyakan layanan ekspor ke Malaysia dan Singapura',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk konsultasi moda, jadwal, dan dokumen yang dibutuhkan.'],
                ],
            ],
            [
                'title' => 'Studi Kasus: UMKM Makanan Olahan Kirim ke Luar Jawa',
                'slug' => 'studi-kasus-umkm-makanan-olahan-kirim-ke-luar-jawa',
                'category' => 'kabar-perusahaan',
                'meta_title' => 'Studi Kasus: UMKM Makanan Olahan Kirim ke Luar Jawa',
                'meta_description' => 'Pengalaman UMKM makanan olahan mengirim produk ke luar Jawa: jadwal pengiriman, kemasan, dan penanganan produk beku.',
                'days_ago' => 13,
                'hour' => 15,
                'lead' => 'Banyak usaha makanan hanya beroperasi di Jawa karena pengiriman dianggap merepotkan. Kenyataannya, dengan kemasan dan jadwal yang tepat, produk ini bisa dikirim ke luar Jawa tanpa kehilangan kualitas.',
                'sections' => [
                    ['Mengenali Masalah Utama',
                        'Makanan olahan sensitif terhadap suhu, kelembapan, dan benturan. Tanpa kemasan yang tepat, produk bisa sampai dengan rasa yang sudah berubah meskipun segelnya masih utuh.'],
                    ['Jadwal Kirim yang Teratur',
                        'Pengiriman terjadwal membantu pemilik usaha merencanakan produksi dan stok tanpa menebak. Jadwal yang tetap juga membuat ongkir lebih mudah diprediksi di akhir bulan.'],
                    ['Hasil untuk Usaha',
                        'Dengan tracking yang transparan, pembeli lebih tenang dan pertanyaan tentang status berkurang. Penjualan ke luar Jawa ternyata bisa menyerap produk dengan harga yang sama.'],
                ],
                'tips_title' => 'Pelajaran dari Kasus Ini',
                'tips' => [
                    'Gunakan kemasan yang menjaga suhu dan kelembapan.',
                    'Kirim terjadwal agar biaya bisa diprediksi.',
                    'Sertakan nomor resi agar pembeli bisa memantau kiriman.',
                    'Pantau status lewat '.self::link('cek resi online', '/cek-resi').' saat ada kiriman ke luar Jawa.',
                ],
                'ctas' => [
                    ['Kirim produk Anda ke luar Jawa',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' untuk menyusun jadwal dan pilihan kemasan.'],
                ],
            ],
            [
                'title' => 'Logistik untuk Bisnis Fashion dan Aksesoris',
                'slug' => 'logistik-untuk-bisnis-fashion-dan-aksesoris',
                'category' => 'tips-tutorial',
                'meta_title' => 'Logistik untuk Bisnis Fashion dan Aksesoris | ATL Express',
                'meta_description' => 'Tips pengiriman untuk bisnis fashion dan aksesoris: kemasan ramping, perhitungan ongkir per kilogram, dan pengemasan yang aman.',
                'days_ago' => 16,
                'hour' => 10,
                'lead' => 'Industri fashion punya tantangan klasik: barang ringan tapi volumenya besar. Akibatnya, ongkir per kilogram terasa mahal. Solusinya ada pada pengemasan dan cara menghitung berat kirim.',
                'sections' => [
                    ['Kemas Ramping, Ongkos Turun',
                        'Hindari kardus besar yang hanya berisi dua atau tiga potong baju. Gunakan kemasan sepadat mungkin, lalu hitung berat sebenarnya setelah dikemas. Penurunan volume ini langsung memangkas ongkir.'],
                    ['Perhatikan Berat Volume',
                        'Karena fashion termasuk kategori ringan tapi besar, berat volumetrik sering lebih menentukan. Minta penjelasan komponen biaya supaya Anda bisa menentukan harga jual dengan tepat.'],
                    ['Konsolidasi Pengiriman',
                        'Pengiriman terjadwal ke kota yang sama membantu biaya per kilogram turun. Untuk toko dengan volume rutin, tanyakan ketersediaan harga kontrak.'],
                ],
                'tips_title' => 'Tips Logistik Fashion',
                'tips' => [
                    'Gunakan kardus sesuai ukuran isi, bukan asal besar.',
                    'Timbang barang setelah pengemasan selesai.',
                    'Tambahkan pelindung untuk barang yang mudah penyok.',
                    'Hitung ongkir di '.self::link('cek tarif', '/cek-tarif').' sebelum menetapkan harga jual.',
                ],
                'ctas' => [
                    ['Tanyakan harga untuk pengiriman fashion',
                        'Sampaikan rata-rata berat paket dan tujuan Anda ke '.self::link('tim kami', '/kontak').' agar kami bisa menghitung opsi terbaik.'],
                ],
            ],
            [
                'title' => 'Kirim Barang dari Solo dan Kota Kecil ke Seluruh Indonesia',
                'slug' => 'kirim-barang-dari-solo-dan-kota-kecil-ke-seluruh-indonesia',
                'category' => 'berita',
                'meta_title' => 'Kirim Barang dari Solo ke Seluruh Indonesia | ATL Express',
                'meta_description' => 'Layanan pengiriman dari Solo dan kota kecil di Jawa ke seluruh Indonesia, termasuk door-to-door, cargo laut, dan udara untuk kebutuhan kilat.',
                'days_ago' => 19,
                'hour' => 12,
                'lead' => 'Solo, Semarang, Malang, dan kota-kota kecil lain di Jawa punya banyak pengirim yang ingin menjangkau pasar luar daerah. Kota seperti ini biasanya dianggap punya jaringan terbatas, padahal tidak selalu demikian.',
                'sections' => [
                    ['Kota Kecil Bukan Berarti Rute Terbatas',
                        'Dengan jaringan mitra, pengiriman dari kota kecil tetap bisa menjangkau berbagai daerah. Yang menentukan adalah jenis layanan, jadwal, dan ketersediaan armada di lokasi pengirim.'],
                    ['Door-to-Door untuk Pemilik Usaha',
                        'Pemilik usaha tidak perlu lagi datang ke kantor cabang untuk mengirim barang. Tim kami bisa menjemput langsung di alamat usaha, termasuk di kawasan pinggiran kota.'],
                    ['Pilihan Moda untuk Tujuan Jauh',
                        'Untuk tujuan di luar Jawa, laut menjadi pilihan paling masuk akal untuk volume besar. Untuk barang kecil yang mendesak, udara tetap tersedia dengan waktu tempuh yang jauh lebih singkat.'],
                ],
                'tips_title' => 'Tips untuk Pengirim di Kota Kecil',
                'tips' => [
                    'Konsolidasikan pengiriman agar ongkir per kilogram lebih hemat.',
                    'Ajukan jadwal tetap bila rutin mengirim ke kota yang sama.',
                    'Siapkan alamat lengkap agar penjemputan berjalan cepat.',
                    'Minta penawaran lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Ajukan jadwal pengiriman dari kota Anda',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' dan sebutkan kota asal serta tujuan rutin pengiriman Anda.'],
                ],
            ],
            [
                'title' => 'Ongkir atau Kecepatan: Kapan Perlu Pilih Cargo Udara',
                'slug' => 'ongkir-atau-kecepatan-kapan-perlu-pilih-cargo-udara',
                'category' => 'tips-tutorial',
                'meta_title' => 'Ongkir atau Kecepatan: Kapan Perlu Cargo Udara?',
                'meta_description' => 'Panduan memilih antara pengiriman murah atau cepat: kapan cargo udara layak dipilih, dan kapan jalur laut lebih masuk akal secara ekonomi.',
                'days_ago' => 22,
                'hour' => 11,
                'lead' => 'Pertanyaan klasik setiap pemilik usaha: hemat ongkir atau kejar kecepatan? Jawabannya bergantung pada nilai barang dan konsekuensi keterlambatan, bukan pada selera.',
                'sections' => [
                    ['Kapan Kecepatan Lebih Bernilai',
                        'Cargo udara layak dipilih ketika barang bernilai tinggi, bersifat cepat rusak, atau keterlambatan menyebabkan kerugian besar. Contohnya sparepart mesin yang menghentikan produksi, masker yang dibutuhkan mendadak, atau dokumen dengan tenggat.'],
                    ['Kapan Harga Jadi Prioritas',
                        'Untuk barang dalam jumlah besar dengan target waktu yang longgar, jalur laut hampir selalu lebih masuk akal. Penghematan pada ongkir sering kali lebih besar daripada nilai barangnya sendiri.'],
                    ['Hitung Dampak, Bukan Sekadar Ongkir',
                        'Bandingkan ongkir tambahan dari udara dengan kerugian yang muncul bila barang terlambat. Untuk sebagian jenis barang, selisih ongkir itu sepadan dengan waktu yang dihemat.'],
                ],
                'tips_title' => 'Tips Memilih Moda',
                'tips' => [
                    'Nilai konsekuensi keterlambatan sebelum memilih moda.',
                    'Minta perbandingan biaya udara dan laut dari tim kami.',
                    'Padatkan kemasan agar biaya udara tetap terkendali.',
                    'Hitung ongkir di '.self::link('cek tarif', '/cek-tarif').' sebagai pembanding.',
                ],
                'ctas' => [
                    ['Bandingkan opsi udara dan laut',
                        'Sampaikan detail paket ke '.self::link('tim kami', '/kontak').' agar kami bisa membantu menghitung selisih biayanya.'],
                ],
            ],
            [
                'title' => 'Tips Logistik untuk Reseller, Agen, dan Distributor',
                'slug' => 'tips-logistik-untuk-reseller-agen-dan-distributor',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Logistik untuk Reseller, Agen, dan Distributor',
                'meta_description' => 'Tips pengiriman untuk reseller dan distributor: harga kontrak, jadwal rutin, stok aman, dan pengurangan ongkir per kilogram.',
                'days_ago' => 25,
                'hour' => 13,
                'lead' => 'Reseller dan distributor bekerja dengan margin yang relatif tipis, sehingga biaya pengiriman bisa menentukan untung atau rugi. Fleksibilitas jadwal menjadi salah satu cara paling efektif menekan ongkir.',
                'sections' => [
                    ['Minta Harga Kontrak untuk Volume Rutin',
                        'Pengiriman dengan volume dan tujuan yang sama secara rutin berpeluang mendapat harga yang lebih baik. Ajukan penawaran tertulis beserta jadwal layanan agar rencana Anda lebih pasti.'],
                    ['Atur Stok dengan Mempertimbangkan Waktu Tempuh',
                        'Menambah stok berarti mengurangi risiko kehabisan barang, tetapi juga menambah biaya penyimpanan. Kalkulasikan waktu tempuh rata-rata ke setiap kota sebelum menentukan jumlah stok aman.'],
                    ['Konsolidasi Kiriman per Periode',
                        'Alih-alih mengirim setiap pesanan satu per satu, kirim dalam satu jadwal mingguan. Ini mengurangi ongkir minimum yang dibayar berulang kali dan memudahkan proses pengemasan di akhir pekan.'],
                ],
                'tips_title' => 'Tips untuk Reseller dan Distributor',
                'tips' => [
                    'Satukan pengiriman dengan tujuan sama dalam satu jadwal.',
                    'Ajukan harga kontrak bila rutin mengirim ke kota yang sama.',
                    'Pantau biaya ongkir per kilogram tiap bulan.',
                    'Diskusikan pola pengiriman lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Minta penawaran untuk kebutuhan distribusi',
                        'Sampaikan kota tujuan, rata-rata volume, dan jadwal pengiriman Anda ke '.self::link('tim kami', '/kontak').'.'],
                ],
            ],
            [
                'title' => 'Kirim Barang ATK dan Perlengkapan Kantor antar Cabang',
                'slug' => 'kirim-barang-atk-dan-perlengkapan-kantor',
                'category' => 'tips-tutorial',
                'meta_title' => 'Kirim Barang ATK dan Perlengkapan Kantor | ATL Express',
                'meta_description' => 'Tips mengirim ATK dan perlengkapan kantor antar cabang: penempelan label penerima, pengemasan berkas, dan kirim door-to-door untuk hemat waktu.',
                'days_ago' => 28,
                'hour' => 8,
                'lead' => 'Pengiriman ATK antar cabang sering dianggap sepele, padalah barang ini menentukan kelancaran kerja. Pengiriman yang rapi dan terdokumentasi membuat pergantian stok lebih mudah diaudit.',
                'sections' => [
                    ['Format Pengiriman antar Kantor',
                        'Sertakan surat jalan atau daftar isi yang mencantumkan jumlah dan jenis barang. Dokumen ini memudahkan penerima melakukan pengecekan tanpa perlu menghubungi pengirim.'],
                    ['Kemas Berkas dan Alat Tulis',
                        'Gunakan map atau kardus kecil untuk berkas, dan bungkus stapler serta alat-alat kecil dengan bubble wrap. Pisahkan barang yang tajam dari berkas agar tidak merusak isi kardus.'],
                    ['Door-to-Door untuk Kantor',
                        'Untuk pengiriman antar kantor di kota yang sama, layanan door-to-door menghemat waktu dan biaya transport yang selama ini keluar untuk mengantar barang sendiri.'],
                ],
                'tips_title' => 'Tips Kirim ATK Kantor',
                'tips' => [
                    'Cantumkan nama perusahaan, divisi, dan nama penerima di label.',
                    'Sertakan daftar isi barang untuk pengecekan cepat.',
                    'Jadwalkan pengiriman di luar jam sibuk bila mungkin.',
                    'Hitung ongkir di '.self::link('cek tarif', '/cek-tarif').' sebagai pembanding biaya.',
                ],
                'ctas' => [
                    ['Jadwalkan pengiriman antar kantor',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' untuk menjadwalkan penjemputan barang kantor Anda.'],
                ],
            ],
            [
                'title' => 'Mengirim Tanaman dan Bibit ke Seluruh Indonesia dengan Aman',
                'slug' => 'mengirim-tanaman-dan-bibit-ke-seluruh-indonesia-dengan-aman',
                'category' => 'tips-tutorial',
                'meta_title' => 'Mengirim Tanaman dan Bibit ke Seluruh Indonesia',
                'meta_description' => 'Cara mengirim tanaman dan bibit ke seluruh Indonesia: syarat izin karantina, kemasan akar, pilih layanan cepat, dan menjaga kelembapan.',
                'days_ago' => 31,
                'hour' => 11,
                'lead' => 'Pengiriman tanaman punya aturan tersendiri karena bisa membawa penyakit ke wilayah baru. Pemahaman soal izin dan kemasan membuat proses ini jauh lebih lancar.',
                'sections' => [
                    ['Perhatikan Izin Karantina',
                        'Tidak semua tanaman boleh dikirim ke semua wilayah. Sebagian jenis memerlukan keterangan karantina dari pihak berwenang. Sampaikan jenis tanaman sejak awal agar tim kami bisa membantu persiapannya.'],
                    ['Kemas Akar dan Media Tanam dengan Benar',
                        'Bungkus media tanam dengan plastik agar tidak mudah kering, lindungi batang dengan penguat, dan gunakan kardus berlubang kecil agar udara masuk tanpa merusak isi.'],
                    ['Pilih Layanan dengan Waktu Tempuh Pendek',
                        'Semakin lama perjalanan, semakin besar risiko tanaman rusak. Untuk tanaman sensitif, gunakan layanan udara atau ekspres dan atur jadwal agar tidak tertahan selama akhir pekan.'],
                ],
                'tips_title' => 'Tips Kirim Tanaman',
                'tips' => [
                    'Konsultasikan jenis tanaman sebelum pengiriman.',
                    'Kemas media tanam agar tidak kering di perjalanan.',
                    'Pilih layanan cepat untuk tanaman yang sensitif.',
                    'Pantau status kiriman lewat '.self::link('cek resi', '/cek-resi').'.',
                ],
                'ctas' => [
                    ['Tanyakan aturan pengiriman tanaman',
                        'Sampaikan jenis tanaman dan tujuan Anda ke '.self::link('tim kami', '/kontak').' agar kami bisa memeriksa persyaratannya.'],
                ],
            ],
            [
                'title' => 'Studi Kasus: Toko Online dengan Ratusan Pesanan per Bulan',
                'slug' => 'studi-kasus-toko-online-dengan-ratusan-pesanan-per-bulan',
                'category' => 'kabar-perusahaan',
                'meta_title' => 'Studi Kasus: Toko Online dengan Ratusan Pesanan per Bulan',
                'meta_description' => 'Kasus operasional toko online dengan ratusan pesanan per bulan: penjadwalan, penjemputan door-to-door, dan tracking yang menurunkan komplain.',
                'days_ago' => 34,
                'hour' => 14,
                'lead' => 'Saat jumlah pesanan naik dari puluhan menjadi ratusan per bulan, pengiriman manual jadi sulit diatur. Anda butuh pola kerja yang bisa diulang setiap minggu.',
                'sections' => [
                    ['Jadwalkan Penjemputan Mingguan',
                        'Alih-alih menunggu pesanan terkumpul, toko ini menetapkan jadwal penjemputan dua kali dalam seminggu. Pola ini membuat alur pekerjaan lebih tenang dan ongkir lebih terencana.'],
                    ['Gabungkan Berdasarkan Tujuan',
                        'Pesanan ke kota yang sama digabung dalam satu paket bila memungkinkan. Selain menghemat ongkir, pengemasan jadi lebih cepat karena bahan yang digunakan lebih sedikit.'],
                    ['Pelacakan sebagai Layanan Pelanggan',
                        'Nomor resi dikirim otomatis ke pembeli setiap kali paket diserahkan. Hal ini menurunkan jumlah pesan masuk dan membuat tim fokus pada hal lain.'],
                ],
                'tips_title' => 'Pelajaran yang Bisa Diterapkan',
                'tips' => [
                    'Tetapkan jadwal penjemputan yang tetap dan diumumkan ke pembeli.',
                    'Gabungkan paket dengan tujuan yang sama bila stok memungkinkan.',
                    'Kirim nomor resi secara otomatis kepada pembeli.',
                    'Minta dukungan operasional lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Siap menaikkan volume pengiriman toko Anda',
                        'Tim kami siap membantu menyusun pola pengiriman. Hubungi kami lewat '.self::link('halaman kontak', '/kontak').'.'],
                ],
            ],
        ]);
    }
}
