<?php

namespace Database\Seeders;

class ArticleTipsSeeder extends BaseArticleSeeder
{
    public function run(): void
    {
        $this->store([
            [
                'title' => 'Tips Memilih Cargo Online yang Murah tapi Tetap Terpercaya',
                'slug' => 'tips-memilih-cargo-online-murah-tetap-terpercaya',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Memilih Cargo Online Murah dan Terpercaya',
                'meta_description' => 'Cara memilih jasa cargo online yang murah tapi tetap aman: bandingkan ongkir, cek tracking, lihat testimoni, dan perhatikan aturan minimum charge.',
                'days_ago' => 3,
                'hour' => 13,
                'lead' => 'Mahal atau murah bukan satu-satunya ukuran kualitas pengiriman. Ekspedisi yang terlihat murah bisa menjadi mahal ketika barang rusak, hilang, atau telat. Berikut cara menimbang pilihan yang tepat.',
                'sections' => [
                    ['Bandingkan Biaya Total, Bukan Harga Timbel',
                        'Hitung ongkir total, yang terdiri dari ongkir dasar, biaya pengemasan, biaya area remote, dan minimum charge untuk kiriman kecil. Rincian angka yang muncul di awal jauh lebih berguna daripada diskon yang hanya berlaku untuk kondisi tertentu.'],
                    ['Cek Sistem Tracking dan Layanan Pelanggan',
                        'Ekspedisi dengan tracking yang bisa diakses pelanggan umumnya lebih dipercaya karena status kiriman bisa diverifikasi. Cari juga kanal komunikasi yang jelas, misalnya WhatsApp atau email, supaya mudah ketika ada kendala.'],
                    ['Perhatikan Ketentuan Barang Tertentu',
                        'Tanyakan aturan untuk barang berbahaya, cairan, atau barang dengan berat lebih dari batas tertentu. Layanan yang menjelaskan batasan dengan jelas cenderung lebih bisa dipercaya.'],
                ],
                'tips_title' => 'Checklist Pilih Cargo',
                'tips' => [
                    'Minta rincian ongkir tertulis sebelum menyetujui pengiriman.',
                    'Cek apakah ada minimum weight atau minimum charge untuk paket kecil.',
                    'Pastikan ada nomor resi dan pembaruan status untuk setiap kiriman.',
                    'Simpan kontak CS resmi untuk kasus sulit.',
                ],
                'ctas' => [
                    ['Bandingkan pilihan Anda dengan ATL Express',
                        'Lihat rincian layanan kami di '.self::link('halaman layanan', '/layanan').' dan hitung ongkir di '.self::link('cek tarif', '/cek-tarif').'.'],
                ],
            ],
            [
                'title' => 'Cara Menghitung Ongkir: Berat Aktual dan Berat Volumetrik',
                'slug' => 'cara-menghitung-ongkir-berat-aktual-dan-berat-volumetrik',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cara Menghitung Ongkir Berat dan Volumetrik | ATL Express',
                'meta_description' => 'Panduan menghitung ongkir cargo: berat aktual, berat volumetrik, minimum charge, dan cara menghitung biaya agar tidak kaget di akhir pengiriman.',
                'days_ago' => 6,
                'hour' => 10,
                'lead' => 'Banyak orang kaget menerima tagihan ongkir yang lebih besar dari perkiraan. Penyebab utamanya hampir selalu sama, yaitu berat volumetrik. Memahami perhitungan ini membantu Anda merencanakan ongkir dengan lebih realistis.',
                'sections' => [
                    ['Berat Aktual dan Berat Volumetrik',
                        'Berat aktual adalah berat barang sebagaimana adanya, sedangkan berat volumetrik dihitung dari ukuran paket. Umumnya ekspedisi mengambil angka yang lebih besar, sehingga barang yang ringan tapi berukuran besar bisa terasa mahal untuk dikirim.'],
                    ['Rumus yang Perlu Anda Ingat',
                        'Rumus paling umum adalah panjang x lebar x tinggi dalam sentimeter, lalu hasilnya dibagi dengan pembagi volumetrik yang berlaku. Nilai pembagi berbeda antar ekspedisi, jadi pastikan menanyakan angka yang dipakai perusahaan pilihan Anda.'],
                    ['Minimum Charge dan Dampaknya',
                        'Banyak ekspedisi menetapkan ongkir minimum untuk kiriman kecil. Artinya, paket 1 kilogram dan paket 5 kilogram bisa saja memiliki ongkir yang mirip, sehingga menggabungkan beberapa barang jadi satu paket sering lebih hemat.'],
                ],
                'tips_title' => 'Tips Efisiensi Ongkir',
                'tips' => [
                    'Hitung sendiri dulu perkiraan berat volumetrik sebelum pengemasan final.',
                    'Padatkan isi kardus agar volumenya tidak membengkak.',
                    'Gabungkan beberapa produk menjadi satu paket bila tujuan sama.',
                    'Minta konfirmasi pembagi volumetrik lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Hitung perkiraan ongkir Anda',
                        'Gunakan '.self::link('kalkulator cek tarif', '/cek-tarif').' untuk melihat estimasi biaya sebelum barang diserahkan.'],
                ],
            ],
            [
                'title' => 'Tips Menulis Alamat Penerima agar Tidak Salah Kirim',
                'slug' => 'tips-menulis-alamat-penerima-agar-tidak-salah-kirim',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Menulis Alamat Penerima agar Tidak Salah Kirim',
                'meta_description' => 'Cara menulis alamat pengiriman yang lengkap dan jelas: nama penerima, nomor telepon, kode pos, patokan lokasi, dan kesalahan yang sering terjadi.',
                'days_ago' => 9,
                'hour' => 15,
                'lead' => 'Salah kirim sering berawal dari alamat yang kurang lengkap. Sekecil apa pun selisih nama atau nomor telepon, dampaknya bisa berupa kiriman yang kembali ke pengirim dengan biaya tambahan.',
                'sections' => [
                    ['Enam Elemen Wajib dalam Alamat',
                        'Alamat yang baik memuat nama penerima, nomor telepon aktif, nama jalan, nomor rumah, kelurahan dan kecamatan, serta kota dan provinsi. Kode pos membantu kurir menemukan lokasi lebih cepat dan mengurangi risiko salah antar.'],
                    ['Tambahkan Patokan yang Jelas',
                        'Untuk daerah dengan gang kecil atau rumah bernomor sama, tuliskan patokan seperti nama masjid, sekolah, atau toko terdekat. Patokan ini sangat membantu kurir lokal yang mungkin belum mengenal lingkungan tersebut.'],
                    ['Konfirmasi kepada Penerima',
                        'Sebelum barang dikirim, pastikan nama dan nomor telepon yang dicantumkan memang milik penerima. Untuk pengiriman ke kantor, cantumkan nama perusahaan dan divisi agar barang tidak tertahan di meja resepsionis.'],
                ],
                'tips_title' => 'Contoh Alamat yang Baik',
                'tips' => [
                    'Tulis nama penerima lengkap sesuai identitas, bukan nama panggilan saja.',
                    'Sertakan nomor WhatsApp yang aktif dan mudah dihubungi.',
                    'Tambahkan catatan singkat bila ada patokan atau aturan penerimaan di lokasi tujuan.',
                    'Kirim data alamat ke '.self::link('tim kami', '/kontak').' untuk pengecekan sebelum jadwal penjemputan.',
                ],
                'ctas' => [
                    ['Cek kembali data alamat Anda',
                        'Kirimkan detail alamat ke '.self::link('halaman kontak', '/kontak').' agar tim kami memverifikasi sebelum barang dikirim.'],
                ],
            ],
            [
                'title' => 'Sepuluh Kesalahan Umum Saat Mengirim Barang via Ekspedisi',
                'slug' => 'sepuluh-kesalahan-umum-saat-mengirim-barang-via-ekspedisi',
                'category' => 'tips-tutorial',
                'meta_title' => '10 Kesalahan Umum Saat Mengirim Barang via Ekspedisi',
                'meta_description' => 'Kesalahan yang sering terjadi saat kirim barang: alamat kurang lengkap, kemasan lemah, tidak menimbang barang, dan cara_ES_CARA menghindarinya.',
                'days_ago' => 12,
                'hour' => 8,
                'lead' => 'Sebagian besar masalah pengiriman bermula dari kesalahan kecil yang sebenarnya mudah dihindari. Berikut sepuluh kesalahan yang paling sering terjadi beserta cara mengatasinya.',
                'sections' => [
                    ['Kesalahan pada Data dan Pengemasan',
                        'Alamat tidak lengkap, nama penerima salah, kemasan yang terlalu tipis, dan tidak adanya bubble wrap untuk barang rapuh adalah empat kesalahan yang paling sering muncul. Semuanya bisa dicegah hanya dengan pengecekan singkat sebelum barang diserahkan.'],
                    ['Kesalahan pada Perhitungan dan Dokumen',
                        'Menyampaikan berat yang tidak sesuai kenyataan, tidak menyimpan bukti pengiriman, dan lupa memasukkan dokumen yang dibutuhkan penerima sering menjadi hambatan di akhir perjalanan. Simpan salinan dokumen dan foto kondisi barang setiap kali mengirim.'],
                    ['Kesalahan pada Timing dan Komunikasi',
                        'Mengirim di hari tanpa operasional, tidak menanyakan jadwal keberangkatan, dan jarang memantau status kiriman membuat pengirim kehilangan kendali. Jadwalkan pengiriman beberapa hari sebelum tenggat pelanggan dan cek status secara berkala.'],
                ],
                'tips_title' => 'Cara Menghindarinya',
                'tips' => [
                    'Baca ulang seluruh data pengiriman sebelum konfirmasi.',
                    'Gunakan bahan pengemas yang sesuai karakteristik barang.',
                    'Simpan foto barang, kemasan, dan nomor resi.',
                    'Pantau status lewat '.self::link('cek resi online', '/cek-resi').' dan hubungi CS bila ada selisih.',
                ],
                'ctas' => [
                    ['Kirim tanpa salah dengan bantuan tim kami',
                        'Konsultasikan rencana pengiriman Anda di '.self::link('halaman kontak', '/kontak').' sebelum barang diserahkan.'],
                ],
            ],
            [
                'title' => 'Tips Cek Hasil Kiriman dan Simpan Bukti Pengiriman',
                'slug' => 'tips-cek-hasil-kiriman-dan-simpan-bukti-pengiriman',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Cek Hasil Kiriman dan Simpan Bukti Pengiriman',
                'meta_description' => 'Cara memeriksa kondisi barang saat diterima, mendokumentasikan kerusakan, dan menyimpan bukti pengiriman untuk keperluan klaim di ATL Express.',
                'days_ago' => 15,
                'hour' => 11,
                'lead' => 'Barang yang tiba dalam kondisi baik adalah hasil akhir dari proses yang panjang. Pemeriksaan singkat saat barang diterima melindungi kedua pihak dan membuat penyelesaian masalah jauh lebih cepat.',
                'sections' => [
                    ['Cek Kondisi Paket secara fisik',
                        'Saat membuka paket, periksa segel, kardus, dan bagian dalam satu per satu. Untuk barang elektronik, nyalakan sebentar untuk memastikan fungsi utama berjalan normal. Catat kerusakan sekecil apa pun karena akan sangat membantu saat mengajukan klaim.'],
                    ['Dokumentasikan dengan Foto',
                        'Ambil foto kemasan sebelum dibuka, kondisi barang saat dibuka, serta bagian yang rusak. Untuk kerusakan yang tidak terlihat dari luar, foto kondisi barang sebelum dikemas saat pengiriman juga berguna sebagai pembanding.'],
                    ['Pelaporan Segera bila Ada Masalah',
                        'Laporkan kerusakan dalam 24 jam setelah barang diterima, disertai nomor resi, foto, dan invoice barang. Tim kami membantu menelusuri masalah berdasarkan data tersebut.'],
                ],
                'tips_title' => 'Checklist Saat Barang Diterima',
                'tips' => [
                    'Periksa segel dan kardus sebelum membuka isi paket.',
                    'Cocokkan barang dengan daftar isi yang dilampirkan.',
                    'Simpan kemasan asli sampai masalah selesai atau barang dipastikan baik.',
                    'Laporkan kendala melalui '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Butuh panduan klaim?',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' dan siapkan nomor resi serta foto kondisi barang.'],
                ],
            ],
            [
                'title' => 'Tips Mengirim Elektronik, Peralatan Rumah, dan Sparepart',
                'slug' => 'tips-mengirim-elektronik-peralatan-rumah-dan-sparepart',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Mengirim Barang Elektronik dan Sparepart | ATL Express',
                'meta_description' => 'Cara mengirim elektronik, peralatan rumah, dan sparepart mesin dengan aman: bubble wrap, pelindung sudut, dan penanganan komponen sensitif.',
                'days_ago' => 18,
                'hour' => 14,
                'lead' => 'Barang elektronik punya dua tantangan: rusak karena benturan dan rusak karena kelembapan. Dengan pengemasan yang tepat, kedua risiko itu bisa ditekan seminimal mungkin.',
                'sections' => [
                    ['Lindungi Komponen yang Rentan',
                        'Bungkus tiap unit elektronik dengan bubble wrap, lalu tambahkan pelindung sudut pada bagian yang tajam. Untuk laptop dan perangkat portabel, gunakan lapisan busa di antara layar dan keyboard supaya layar tidak tergores.'],
                    ['Kendalikan Kelembapan',
                        'Di perjalanan jauh atau di wilayah yang lembap, tambahkan bahan pengering di dalam kemasan. Untuk barang elektronik yang sudah finishing, hindari mengemas barang yang masih lembap karena uap air bisa merusak jalur di motherboard.'],
                    ['Komponen Kaku dan Berat',
                        'Sparepart mesin, pompa, dan peralatan industri sering memiliki bobot yang membuat kardus mudah sobek. Perkuat di setiap sudut dan tuliskan berat barang pada label agar tim penanganan bisa menggunakan alat angkat yang tepat.'],
                ],
                'tips_title' => 'Tips Pengemasan Elektronik',
                'tips' => [
                    'Gunakan kardus dengan ukuran sedikit lebih besar dari barang agar bisa diberi bantalan.',
                    'Tandai kolom barang berat pada formulir pengiriman.',
                    'Kirim tester atau kabel asli yang menyertai barang agar penerima bisa memeriksa fungsi.',
                    'Pertimbangkan asuransi bila nilai barang cukup tinggi.',

                ],
                'ctas' => [
                    ['Konsultasikan pengemasan barang elektronik',
                        'Ceritakan jenis barang Anda lewat '.self::link('halaman kontak', '/kontak').' agar tim kami menyiapkan solusi pengemasan yang tepat.'],
                ],
            ],
            [
                'title' => 'Tips Mengirim Produk Segar dan Barang Beku',
                'slug' => 'tips-mengirim-produk-segar-dan-barang-beku',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Mengirim Produk Segar dan Barang Beku | ATL Express',
                'meta_description' => 'Cara mengirim produk segar, es krim, dan barang beku: pilih layanan ekspres, gunakan styrofoam dan ice pack, serta hindari waktu tempuh yang terlalu lama.',
                'days_ago' => 21,
                'hour' => 16,
                'lead' => 'Barang beku dan produk segar punya batas waktu yang jelas. Melewati batas itu berarti kualitas produk turun drastis, meskipun barang masih sampai utuh. Karena itu, waktu tempuh harus jadi prioritas utama.',
                'sections' => [
                    ['Pilih Layanan yang Tercepat',
                        'Gunakan layanan udara atau ekspres untuk produk yang mudah rusak. Ini keputusan paling penting, karena kemasan terbaik pun tidak akan menahan perubahan suhu yang berlangsung berjam-jam.'],
                    ['Kemasan yang Menahan Suhu',
                        'Gunakan styrofoam yang dikempit di dalam kardus, isi ruang kosong dengan ice pack, dan tutup bagian atas dengan rapat. Untuk produk segar seperti buah dan sayur, gunakan ventilasi agar barang tidak cepat membusuk.'],
                    ['Kirim di Waktu yang Tepat',
                        'Kirim pada awal minggu agar barang tidak tertahan selama akhir pekan, dan hindari mengirim tepat sebelum hari libur. Beri tahu tim kami jika isi kiriman perlu penanganan cepat agar prioritasnya jelas sejak awal.'],
                ],
                'tips_title' => 'Tips Kirim Produk Beku',
                'tips' => [
                    'Gunakan ice pack atau gel beku yang membantu mempertahankan suhu.',
                    'Kemas dalam styrofoam dan kencangkan dengan kardus luar.',
                    'Kirim di hari kerja dan informasikan ke CS bahwa isi perlu ditangani cepat.',
                    'Pantau status kiriman melalui '.self::link('cek resi', '/cek-resi').'.',
                ],
                'ctas' => [
                    ['Tanyakan layanan untuk kirim beku',
                        'Tim kami siap membantu lewat '.self::link('halaman kontak', '/kontak').' untuk memilih moda dan kemasan yang sesuai.'],
                ],
            ],
            [
                'title' => 'Cara Membuat Label Pengiriman yang Mempermudah Kurir',
                'slug' => 'cara-membuat-label-pengiriman-yang-mempermudah-kurir',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cara Membuat Label Pengiriman yang Mempermudah Kurir',
                'meta_description' => 'Tips membuat label pengiriman yang jelas: isi data penerima, tambahkan penanda handling, dan hindari kesalahan yang biasa terjadi saat pelabelan paket.',
                'days_ago' => 24,
                'hour' => 13,
                'lead' => 'Label yang jelas membuat proses penanganan lebih cepat dan mengurangi kesalahan antar kiriman. Sebaliknya, label yang ambigu bisa membuat paket tertahan atau bahkan salah tujuan.',
                'sections' => [
                    ['Isi Data Penerima Secara Lengkap',
                        'Tulis nama penerima, nomor telepon, alamat lengkap, dan kode pos dengan huruf besar agar mudah dibaca. Tempelkan label pada bidang rata dan jauhkan dari lipatan kardus agar tidak sobek saat ditangani.'],
                    ['Tambahkan Penanda Handling',
                        'Gunakan penanda seperti FRAGILE, HANDLE WITH CARE, atau THIS SIDE UP untuk barang yang membutuhkan perhatian khusus. Penanda ini membantu petugas menyusun dan membongkar paket dengan urutan yang benar.'],
                    ['Hindari Kesalahan yang Sering Terjadi',
                        'Label yang ditempel miring, tinta yang luntur karena ditempel pada permukaan kotor, dan alamat yang ditulis di bawah barcode sering menjadi penyebab data tidak terbaca. Pastikan permukaan bersih dan label ditempel dengan rapi.'],
                ],
                'tips_title' => 'Checklist Pelabelan',
                'tips' => [
                    'Cetak label dengan kertas yang tidak mudah sobek dan tidak mudah lapuk.',
                    'Tempelkan label minimal dua sisi untuk paket berukuran besar.',
                    'Simpan salinan data label di perangkat sebagai cadangan.',
                    'Minta bantuan pelabelan melalui '.self::link('halaman kontak', '/kontak').' bila mengirim dalam jumlah banyak.',
                ],
                'ctas' => [
                    ['Butuh bantuan membuat label dalam jumlah banyak?',
                        'Tim kami dapat membantu lewat '.self::link('halaman kontak', '/kontak').' untuk kebutuhan pengiriman rutin Anda.'],
                ],
            ],
            [
                'title' => 'Tips Hemat Ongkir untuk Pengiriman Rutin Setiap Minggu',
                'slug' => 'tips-hemat-ongkir-untuk-pengiriman-rutin',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Hemat Ongkir untuk Pengiriman Rutin | ATL Express',
                'meta_description' => 'Cara menghemat ongkir untuk pengiriman rutin: konsolidasi muatan, jadwal tetap, harga kontrak, dan pengemasan yang efisien.',
                'days_ago' => 27,
                'hour' => 9,
                'lead' => 'UMKM yang mengirim barang setiap hari punya peluang besar untuk menurunkan ongkir. Kuncinya bukan lagi menawar, melainkan merapikan pola pengiriman agar muatan lebih efisien.',
                'sections' => [
                    ['Konsolidasi Muatan per Rute',
                        'Barang dari beberapa pengirim ke kota yang sama bisa dikirim bersama dalam satu jadwal. Raum kendaraan terisi lebih penuh, sehingga biaya transport per kilogram turun dan Anda tidak perlu membayar minimum charge berulang kali.'],
                    ['Jadwal Tetap dan Harga Kontrak',
                        'Pengiriman dengan jadwal yang sama setiap minggu membantu kami merencanakan muatan dan armada lebih baik. Untuk volume rutin, tanyakan ketersediaan harga kontrak yang membuat ongkir lebih pasti.'],
                    ['Efisiensi Pengemasan',
                        'Menggunakan ukuran kardus yang sesuai isi barang mengurangi volume yang tidak terpakai. Kardus yang terlalu besar bukan hanya menambah ongkir, tetapi juga menambah risiko barang bergeser selama perjalanan.'],
                ],
                'tips_title' => 'Langkah Penghematan',
                'tips' => [
                    'Catat ongkir per kilogram tiap minggu untuk melihat pola biaya.',
                    'Gunakan jadwal pengiriman tetap agar mudah direncanakan.',
                    'Gabung barang dengan tujuan sama untuk menghemat ongkir.',
                    'Tanyakan harga kontrak lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Minta penawaran untuk pengiriman rutin',
                        'Sampaikan volume dan tujuan pengiriman Anda ke '.self::link('tim kami', '/kontak').' agar kami bisa menyusun skema yang paling hemat.'],
                ],
            ],
            [
                'title' => 'Tips Mengirim Dokumen Penting, Kontrak, dan Berkas Hukum',
                'slug' => 'tips-mengirim-dokumen-penting-kontrak-dan-berkas-hukum',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Mengirim Dokumen Penting dan Berkas Hukum | ATL Express',
                'meta_description' => 'Cara mengirim dokumen penting, kontrak, dan berkas hukum dengan aman: gunakan map atau amplop kertas keras, dan layanan ekspres.',
                'days_ago' => 30,
                'hour' => 10,
                'lead' => 'Dokumen penting sering dianggap sepele karena bentuknya ringan, padahal dampaknya besar. Lipatan yang keliru, kertas yang basah, atau amplop yang sobek bisa menjadi masalah serius.',
                'sections' => [
                    ['Gunakan Amplop atau Map yang Kuat',
                        'Untuk dokumen kertas, gunakan amplop cokelat yang diperkuat atau map keras. Masukkan lembar di dalam plastik bening agar terlindungi dari air, dan gunakan staple untuk menjaga urutan halaman.'],
                    ['Kirim dengan Layanan Ekspres',
                        'Dokumen hukum dan kontrak sering punya tenggat yang ketat. Pilih layanan udara atau ekspres bila tanggalnya sensitif, dan konfirmasi ke penerima soal waktu terbaik untuk menerima paket.'],
                    ['Arsipkan Salinan',
                        'Sebelum dikirim, simpan salinan digital atau foto setiap halaman. Selain memudahkan klaim bila paket hilang, arsip ini juga berguna saat dokumen perlu ditunjukkan kembali.'],
                ],
                'tips_title' => 'Tips Kirim Dokumen',
                'tips' => [
                    'Gunakan amplop anti air untuk dokumen sensitif.',
                    'Tuliskan nomor telepon penerima yang aktif.',
                    'Kirim salinan digital ke penerima sebagai cadangan.',
                    'Pantau status kiriman lewat '.self::link('cek resi', '/cek-resi').'.',
                ],
                'ctas' => [
                    ['Kirim dokumen dengan layanan ekspres',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk menanyakan opsi pengiriman dokumen.'],
                ],
            ],
            [
                'title' => 'Tips Mengirim Cargo Berat dan Tonase Besar',
                'slug' => 'tips-mengirim-cargo-berat-dan-tonase-besar',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Mengirim Cargo Berat dan Tonase Besar | ATL Express',
                'meta_description' => 'Panduan mengirim cargo berat dalam jumlah besar: pembagian muatan, pemilihan kendaraan, tips penanganan alat berat, dan penghematan biaya.',
                'days_ago' => 33,
                'hour' => 13,
                'lead' => 'Pengiriman barang dalam jumlah besar punya aturan main yang berbeda. Perencanaan yang baik membuat biaya turun dan risiko kerusakan berkurang, sedangkan perencanaan yang terburu-buru sebaliknya.',
                'sections' => [
                    ['Bagi Muatan agar Mudah Dihandle',
                        'Kargo berat lebih baik dibagi menjadi beberapa unit yang lebih kecil dengan berat wajar. Selain lebih mudah ditangani, pembagian ini mengurangi risiko satu paket berat yang sulit dimuat dan mahal untuk dipindahkan.'],
                    ['Pilih Kendaraan yang Tepat',
                        'Untuk material seperti besi, semen, dan palet, diperlukan kendaraan dengan kapasitas yang sesuai serta alat bongkar muat. Sampaikan detail bobot dan dimensi sejak awal agar tim kami menyiapkan kendaraan yang tepat.'],
                    ['Keamanan dan Penempatan',
                        'Barang berat harus diikat dan ditumpuk dengan benar agar tidak bergeser selama perjalanan. Untuk material berbahaya, ikuti ketentuan pengangkutan yang berlaku dan pastikan label yang diwajibkan terpasang.'],
                ],
                'tips_title' => 'Tips Kirim Tonase Besar',
                'tips' => [
                    'Sampaikan berat total dan dimensi sebelum permintaan penawaran.',
                    'Tanyakan apakah pengiriman bisa dijadwalkan bertahap.',
                    'Pastikan lokasi bongkar muat siap menerima kendaraan besar.',
                    'Diskusikan rencana lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Rencanakan pengiriman tonase besar',
                        'Hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk berdiskusi soal perhitungan beban dan kebutuhan kendaraan.'],
                ],
            ],
            [
                'title' => 'Tips Kirim Barang Saat Musim Liburan agar Tidak Tertunda',
                'slug' => 'tips-kirim-barang-saat-musim-liburan-agar-tidak-tertunda',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Kirim Barang Saat Musim Liburan agar Tidak Tertunda | ATL Express',
                'meta_description' => 'Persiapan kirim barang menjelang libur panjang: kirim lebih awal, pilih layanan dengan rute tetap, dan pantau status saat volume pengiriman melonjak.',
                'days_ago' => 36,
                'hour' => 12,
                'lead' => 'Menjelang libur panjang, volume pengiriman naik drastis sementara kapasitas jaringan terbatas. Kiriman yang biasanya tiba dalam tiga hari bisa memerlukan waktu jauh lebih lama kalau dikirim di saat yang paling padat.',
                'sections' => [
                    ['Kirim Lebih Awal dari Tenggat',
                        'Kirim barang satu sampai dua minggu sebelum tanggal yang dibutuhkan penerima. Pengiriman lebih awal memberi ruang waktu jika terjadi penundaan akibat cuaca atau penyesuaian jadwal kapal.'],
                    ['Pilih Layanan yang Tetap Berjalan',
                        'Pada periode libur, layanan dengan rute tetap cenderung lebih dapat diandalkan daripada layanan yang jadwalnya berubah. Tim kami dapat membantu memilih layanan yang paling aman untuk tanggal kiriman Anda.'],
                    ['Pantau Status secara Rutin',
                        'Saat volume melonjak, pembaruan status bisa lebih jarang. Periksa nomor resi secara berkala lewat '.self::link('cek resi online', '/cek-resi').' dan hubungi CS bila status tidak bergerak dalam beberapa hari.'],
                ],
                'tips_title' => 'Persiapan Sebelum Liburan',
                'tips' => [
                    'Daftarkan jadwal pengiriman mingguan Anda lebih awal.',
                    'Stok bahan pengemasan sebelum puncak periode.',
                    'Siapkan daftar nomor resi yang perlu dipantau.',
                    'Konfirmasi rencana kirim lewat '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Rencanakan pengiriman menjelang hari libur',
                        'Tim kami siap membantu lewat '.self::link('halaman kontak', '/kontak').' untuk mengatur jadwal kirim Anda.'],
                ],
            ],
        ]);
    }
}
