<?php

namespace Database\Seeders;

class ArticleLayananSeeder extends BaseArticleSeeder
{
    public function run(): void
    {
        $this->store([
            [
                'title' => 'Kenapa Pengiriman Cargo Online Jadi Pilihan Utama UMKM',
                'slug' => 'kenapa-pengiriman-cargo-online-jadi-pilihan-utama-umkm',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cargo Online untuk UMKM: Cepat, Murah, Terpercaya | ATL Express',
                'meta_description' => 'Alasan UMKM beralih ke pengiriman cargo online: harga transparan, tracking real-time, dan jangkauan seluruh Indonesia. Panduan lengkapnya ada di sini.',
                'days_ago' => 2,
                'hour' => 8,
                'lead' => 'Dulu, banyak usaha kecil dan menengah mengirim barang masih bolak-balik ke kantor pos atau agen kargo hanya untuk bertanya ongkir. Hari ini semuanya bisa selesai dari HP: cek tarif, pesan penjemputan, dan lacak paket dari satu layar. Perubahan kecil bagi konsumen, tetapi besar untuk efisiensi usaha.',
                'sections' => [
                    ['Harga Jadi Jauh Lebih Terlihat',
                        'Saat ongkir disembunyikan di balik percakapan WhatsApp, pemilik usaha sulit memperkirakan margin. Sistem tarif online membuat hitungan ongkir terbuka sejak awal: berapa kilogram, berapa volume, dan berapa biaya layanan. Anda bisa membandingkan beberapa opsi sebelum memutuskan tanpa perlu banyak tawar-menawar.',
                        [
                            'Tarif dihitung otomatis dari berat dan volume barang',
                            'Biaya tambahan seperti packing dan asuransi ditampilkan terpisah',
                            'Tidak ada biaya tersembunyi yang baru muncul di akhir perjalanan',
                        ]],
                    ['Tracking Menghemat Waktu Tim',
                        'Pertanyaan paling sering masuk ke tim kami adalah "barang saya sudah sampai mana?". Dengan nomor resi, status perjalanan bisa dipantau kapan saja. Tim admin tidak lagi menjawab pertanyaan yang sama berulang kali, dan pelanggan mendapat jawaban yang konsisten.',
                        [
                            'Status diterima, dalam proses, dalam perjalanan, dan selesai diantarkan',
                            'Riwayat perjalanan tersimpan rapi untuk setiap nomor resi',
                            'Informasi penting langsung dikirim ke kontak penerima',
                        ]],
                    ['Ongkir Bisa Lebih Irit dengan Pengiriman Rutin',
                        'Pengiriman harian ke tujuan yang sama membuat volume cargo terkumpul. Kiriman yang dikonsolidasikan dalam jaringan yang sama membuat ongkir per kilogram turun, terutama untuk rute Jawa ke Sumatera, Kalimantan, atau Sulawesi. Rincian rute bisa ditanyakan langsung lewat '.self::link('halaman kontak', '/kontak').'.'],
                ],
                'tips_title' => 'Langkah Awal Pindah ke Cargo Online',
                'tips' => [
                    'Siapkan data pengiriman dengan rapi: nama penerima, alamat lengkap, nomor telepon aktif, dan kode pos.',
                    'Minta estimasi ongkir tertulis agar bisa dipakai sebagai acuan harga jual.',
                    'Gunakan layanan tracking sejak order pertama supaya reputasi toko tetap terjaga.',
                    'Simpan bukti pengiriman berupa foto paket dan nomor resi jika barang bermasalah.',
                ],
                'ctas' => [
                    ['Cek tarif cargo online sekarang',
                        'Buka '.self::link('halaman cek tarif', '/cek-tarif').' lalu isi kota asal dan kota tujuan. Estimasi ongkir langsung tampil tanpa perlu daftar lebih dulu.'],
                ],
            ],
            [
                'title' => 'ATL Express: Layanan Cargo Online yang Cepat, Murah, dan Terpercaya',
                'slug' => 'atl-express-layanan-cargo-online-cepat-murah-terpercaya',
                'category' => 'kabar-perusahaan',
                'meta_title' => 'Jasa Cargo Online Cepat, Murah, Terpercaya | ATL Express',
                'meta_description' => 'Kenalan dengan ATL Express: jasa pengiriman cargo online untuk seluruh Indonesia dengan tarif jelas, tracking real-time, serta layanan darat, laut, dan udara.',
                'days_ago' => 4,
                'hour' => 10,
                'lead' => 'ATL Express dibangun dengan satu misi sederhana: pengiriman barang harus terasa mudah, tidak ribet, dan bisa dipertanggungjawabkan. Sejak awal kami memusatkan perhatian pada tiga hal: sistem pemesanan yang sepenuhnya online, jaringan yang menjangkau seluruh Indonesia, dan komunikasi yang terbuka kepada pelanggan.',
                'sections' => [
                    ['Tiga Layanan Utama yang Bisa Dipilih',
                        'Barang ringan dan buruan dikirim lewat udara, barang besar ke luar Jawa lebih masuk akal lewat laut, sedangkan tujuan di dalam jaringan darat cukup jauh lebih cepat diantar dengan moda darat. Semua layanan punya penjelasan terpisah di '.self::link('halaman layanan', '/layanan').' supaya Anda bisa memilih dengan tenang sebelum memesan.'],
                    ['Sistem Online dari Awal sampai Akhir',
                        'Pemesanan, penjemputan barang, dan pelaporan status berjalan lewat kanal digital. Kurir kami datang ke alamat pengirim sesuai jadwal yang ditentukan, sementara status kiriman bisa dipantau melalui nomor resi. Tidak ada lagi buku catatan yang harus dicari ketika pelanggan menanyakan kiriman.'],
                    ['Harga yang Tidak Menyesatkan',
                        'Tarif dihitung dengan parameter yang jelas: berat, volume, jarak rute, dan jenis layanan. Melalui pemesanan online, Anda melihat angka yang sama dengan yang dipakai tim kami saat membuat airway bill, sehingga tidak ada lagi selisih ongkir di akhir pengiriman.'],
                ],
                'tips_title' => 'Fitur yang Membantu Pengiriman Anda',
                'tips' => [
                    'Fitur '.self::link('cek resi online', '/cek-resi').' untuk memantau posisi kiriman kapan saja tanpa perlu menghubungi tim CS.',
                    'Layanan Door-to-Door menghemat waktu dan biaya transport pengirim ke kantor cabang.',
                    'Asuransi cargo tersedia untuk barang bernilai tinggi atau mudah rusak.',
                    'Tim CS aktif di WhatsApp untuk menjawab pertanyaan jadwal, tarif, dan dokumen.',
                ],
                'ctas' => [
                    ['Mulai kirim hari ini juga',
                        'Buat pesanan lewat '.self::link('sistem cek tarif', '/cek-tarif').' atau hubungi tim kami di '.self::link('halaman kontak', '/kontak').' untuk konsultasi rute dan jadwal keberangkatan.'],
                ],
            ],
            [
                'title' => 'Cara Pesan Pengiriman Barang Online di ATL Express, Cuma 3 Menit',
                'slug' => 'cara-pesan-pengiriman-barang-online-di-atl-express',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cara Pesan Pengiriman Online di ATL Express, Cuma 3 Menit',
                'meta_description' => 'Tutorial singkat cara memesan jasa kirim online di ATL Express: isi data, pilih layanan, konfirmasi, lalu pantau nomor resi sampai barang sampai tujuan.',
                'days_ago' => 6,
                'hour' => 14,
                'lead' => 'Tidak perlu formulir panjang atau datang ke kantor. Pemesanan pengiriman online di ATL Express cukup beberapa langkah singkat, dan seluruh prosesnya terdokumentasi dengan nomor resi yang bisa dilacak kapan saja.',
                'sections' => [
                    ['Langkah 1: Isi Data Pengiriman',
                        'Siapkan nama pengirim dan penerima, alamat lengkap, kota tujuan, nomor telepon, serta berat dan dimensi paket. Data yang lengkap sejak awal membuat proses penjemputan berjalan tanpa revisi ulang dan membantu tim kami memilih moda pengiriman paling hemat.'],
                    ['Langkah 2: Dapatkan Penawaran dan Konfirmasi',
                        'Setelah data masuk, tim kami mengirim estimasi ongkir beserta jadwal penjemputan. Begitu ongkos disetujui, kurir kami dijadwalkan untuk mengambil barang di alamat yang Anda cantumkan.'],
                    ['Langkah 3: Pantau dan Terima',
                        'Begitu barang diterima, nomor resi aktif dan bisa dilacak lewat '.self::link('layanan cek resi', '/cek-resi').'. Pembaruan status dikirim otomatis, dan tim kami menghubungi penerima ketika kiriman sudah berada di lokasi pengambilan.'],
                ],
                'tips_title' => 'Agar Prosesnya Lancar',
                'tips' => [
                    'Tulis alamat lengkap sampai tingkat RT atau RW, patokan, dan kode pos.',
                    'Kirim foto barang saat pengemasan bila perlu peninjauan keandalan kemasan.',
                    'Pastikan nomor penerima aktif dan bisa dihubungi pada jam kerja.',
                    'Simpan nomor resi di satu folder agar mudah dicari saat dibutuhkan.',
                ],
                'ctas' => [
                    ['Siapkan paket Anda sekarang',
                        'Buka '.self::link('halaman cek tarif', '/cek-tarif').' untuk estimasi ongkir, atau tanya langsung ke tim kami kapan pun lewat '.self::link('form kontak', '/kontak').'.'],
                ],
            ],
            [
                'title' => 'Cek Resi Online: Pantau Kiriman Real-Time Kapan Saja',
                'slug' => 'cek-resi-online-pantau-kiriman-real-time',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cek Resi Online Real-Time | ATL Express',
                'meta_description' => 'Cara cek resi online dan memantau status pengiriman cargo di ATL Express, termasuk tips membaca status kiriman dan menangani keluhan saat barang bermasalah.',
                'days_ago' => 8,
                'hour' => 11,
                'lead' => 'Ketenangan adalah hak setiap pengirim. Dengan fitur '.self::link('cek resi online', '/cek-resi').', Anda bisa melihat perpindahan barang tanpa perlu menelepon CS. Status diperbarui otomatis pada setiap tahap penanganan.',
                'sections' => [
                    ['Empat Tahap Status yang Perlu Anda Kenali',
                        'Setiap kiriman melewati tahap yang jelas: barang diterima di lokasi pengirim, masuk proses sortir dan pengemasan, dalam perjalanan menuju simpul berikutnya, dan selesai diantarkan. Memahami arti tiap tahap memudahkan Anda memperkirakan kapan barang siap diterima.'],
                    ['Kenapa Status Tersendat Tidak Berarti Barang Hilang',
                        'Cargo antar pulau melewati banyak titik: penjemputan, gudang, dock, kapal, transit, lalu kota tujuan. Ada jeda antar tahap, terutama saat menunggu jadwal pelayaran. Selama status terakhir masih menunjukkan proses yang wajar, barang berada di jalur yang benar.'],
                    ['Riwayat yang Membantu Saat Ada Keluhan',
                        'Riwayat status bisa dilampirkan saat Anda menghubungi tim kami. Data ini memudahkan pengecekan di gudang atau di kapal, dan mempercepat penelusuran bila terjadi selisih kiriman atau kerusakan kemasan.'],
                ],
                'tips_title' => 'Tips Agar Tracking Smooth',
                'tips' => [
                    'Cek nomor resi secara berkala, terutama menjelang hari raya saat volume meningkat.',
                    'Simpan tangkapan layar status sebagai bukti bila perlu mengajukan klaim.',
                    'Pastikan nama dan nomor penerima pada airway bill sesuai identitas penerima.',
                    'Hubungi CS lebih awal bila status tidak berubah selama beberapa hari, jangan menunggu lama.',
                ],
                'ctas' => [
                    ['Lacak kiriman Anda sekarang',
                        'Masukkan nomor resi di '.self::link('halaman cek resi', '/cek-resi').' dan lihat posisi barang Anda dalam hitungan detik.'],
                ],
            ],
            [
                'title' => 'Tips Memilih Jasa Ekspedisi Online yang Aman dan Terpercaya',
                'slug' => 'tips-memilih-jasa-ekspedisi-online-yang-aman-dan-terpercaya',
                'category' => 'tips-tutorial',
                'meta_title' => 'Tips Memilih Jasa Ekspedisi Online Aman & Terpercaya',
                'meta_description' => 'Lima hal yang wajib dicek sebelum memilih jasa ekspedisi online: izin operasional, tracking, asuransi, harga transparan, dan kualitas layanan pelanggan.',
                'days_ago' => 10,
                'hour' => 9,
                'lead' => 'Harga termurah belum tentu pilihan terbaik. Ekspedisi yang baik adalah yang barangnya sampai utuh, informasinya jelas, dan setiap pertanyaan bisa dijawab dengan cepat. Berikut beberapa hal yang layak dicek sebelum menitipkan barang.',
                'sections' => [
                    ['Cek Legalitas dan Jangkauan',
                        'Pastikan penyedia jasa memiliki izin operasional transportasi yang jelas dan jangkauan area pelayanaannya mencakup alamat tujuan. Pengiriman ke daerah terpencil membutuhkan pengalaman lokal yang tidak semua ekspedisi miliki.'],
                    ['Perhatikan Sistem Tracking',
                        'Nomor resi tanpa status yang jelas tidak banyak berguna. Layanan dengan tracking online bisa mengurangi pertanyaan bolak-balik dan membuat pengirim serta penerima tahu posisi barang.'],
                    ['Tanyakan Soal Asuransi dan Klaim',
                        'Barang bernilai tinggi perlu aturan yang jelas: nilai ganti maksimum, dokumen yang dibutuhkan, dan batas waktu pengajuan. Ketentuan yang transparan membuat klaim jauh lebih mudah.'],
                    ['Bandingkan Biaya Total, Bukan Ongkir Saja',
                        'Hitung total biaya: ongkir, biaya pengemasan, biaya area remote, dan minimum charge. '.self::link('ATL Express', '/').' menampilkan rincian ini sejak awal supaya perbandingannya adil.'],
                ],
                'tips_title' => 'Checklist Cepat Sebelum Kirim',
                'tips' => [
                    'Cek apakah ada minimum weight atau minimum charge yang tidak Anda ketahui sejak awal.',
                    'Pastikan layanan door-to-door tersedia di daerah penerima.',
                    'Tanyakan aturan khusus untuk barang berbahaya seperti baterai dan aerosol.',
                    'Minta contoh format airway bill atau label yang dipakai perusahaan.',
                ],
                'ctas' => [
                    ['Bandingkan langsung dengan ATL Express',
                        'Lihat layanan yang kami tawarkan di '.self::link('halaman layanan', '/layanan').' dan minta penawaran melalui '.self::link('halaman kontak', '/kontak').'.'],
                ],
            ],
            [
                'title' => 'Door-to-Door: Kiriman Diambil Langsung dari Pintu Anda',
                'slug' => 'layanan-door-to-door-kiriman-diambil-dari-pintu-anda',
                'category' => 'berita',
                'meta_title' => 'Layanan Door-to-Door Pengiriman Barang | ATL Express',
                'meta_description' => 'Layanan door-to-door ATL Express menjemput barang dari alamat pengirim dan mengantar sampai alamat penerima. Praktis untuk UMKM, belanja online, dan pengiriman pribadi.',
                'days_ago' => 12,
                'hour' => 15,
                'lead' => 'Bayangkan barang Anda tidak perlu diantar ke kantor cabang, tidak perlu turun ke jalan, dan tidak perlu menunggu antrean. Layanan Door-to-Door ATL Express menjemput langsung di alamat pengirim lalu mengantarkan ke alamat penerima.',
                'sections' => [
                    ['Cara Kerja Door-to-Door',
                        'Anda menentukan waktu penjemputan, kurir kami datang ke lokasi, barang diperiksa, ditimbang, lalu diberi nomor resi. Barang Anda tidak perlu menunggu di lokasi karena tim kami yang bekerja mengurusnya.'],
                    ['Cocok untuk Siapa',
                        'Layanan ini paling membantu pemilik usaha yang tempat kerjanya tidak dekat dengan pusat distribusi, penjual online yang ingin kirim dari rumah, serta orang tua yang mengirim barang kepada anak yang tinggal di pulau berbeda.'],
                    ['Ketentuan Teknis yang Perlu Disiapkan',
                        'Siapkan alamat lengkap dengan patokan yang mudah ditemukan, nomor telepon yang aktif, serta daftar isi barang bila perlu. Untuk barang besar atau jumlah banyak, beri tahu tim kami agar kendaraan yang sesuai dapat diarahkan.'],
                ],
                'tips_title' => 'Tips Agar Pickup Lancar',
                'tips' => [
                    'Sediakan area pengambilan yang lapang dan mudah diakses kendaraan.',
                    'Kemas barang sebelum jadwal penjemputan agar waktu tidak terbuang.',
                    'Sampaikan instruksi khusus, misalnya barang tidak boleh ditumpuk.',
                    'Pastikan isi kiriman sesuai ketentuan ekspedisi untuk tanaman, hewan, atau cairan berbahaya.',
                ],
                'ctas' => [
                    ['Jadwalkan penjemputan',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' atau pesan layanan door-to-door secara online.'],
                ],
            ],
            [
                'title' => 'Pengiriman Darat, Laut, atau Udara? Pilih yang Paling Sesuai',
                'slug' => 'pengiriman-darat-laut-atau-udara-pilih-yang-paling-sesuai',
                'category' => 'tips-tutorial',
                'meta_title' => 'Cargo Darat, Laut, atau Udara? Panduan Memilih | ATL Express',
                'meta_description' => 'Panduan memilih moda pengiriman cargo: darat untuk area terrestrial, laut untuk barang besar ke luar Jawa, udara untuk barang kilat dan bernilai tinggi.',
                'days_ago' => 14,
                'hour' => 10,
                'lead' => 'Pertanyaan paling sering muncul: "Barang saya sebaiknya dikirim darat, laut, atau udara?" Jawabannya bergantung pada tiga hal, yaitu berapa lama barang boleh tiba, seberapa besar volumenya, dan seberapa sensitif isinya.',
                'sections' => [
                    ['Darat: Andal untuk Jarak Sedang dan Barang Sedang',
                        'Armada darat menjadi pilihan utama untuk pengiriman antarkota di Jawa, ke Bali, dan ke wilayah dengan akses jalan yang baik. Moda ini menawarkan kombinasi biaya dan kecepatan yang seimbang, cocok untuk karton, plastik, dan produk ritel pada umumnya.'],
                    ['Laut: Biaya Termurah untuk Barang Besar',
                        'Untuk cargo dalam jumlah banyak, berat, atau berukuran besar, jalur laut jelas lebih masuk akal. Rincian '.self::link('layanan pengiriman laut', '/layanan/pengiriman-laut').' menjelaskan penanganan bongkar muat dan standar penanganan barang kami.'],
                    ['Udara: Saat Waktu Lebih Penting daripada Biaya',
                        'Dokumen, sparepart mesin, masker, dan produk bernilai tinggi sering butuh sampai dalam hitungan hari. '.self::link('Layanan cargo udara', '/layanan/pengiriman-udara').' menjadi pilihan ketika ketepatan waktu menjadi prioritas utama.'],
                ],
                'tips_title' => 'Aturan Sederhana untuk Memilih',
                'tips' => [
                    'Butuh sampai satu sampai tiga hari dan tidak terlalu berat? Pertimbangkan udara.',
                    'Volume besar dengan target waktu longgar? Laut hampir selalu lebih hemat.',
                    'Tujuan di dalam jaringan darat? Darat adalah opsi paling ringkas.',
                    'Bingung? Minta rekomendasi mode dari tim kami berdasarkan data paket Anda.',
                ],
                'ctas' => [
                    ['Minta rekomendasi mode pengiriman',
                        'Kirim detail paket Anda lewat '.self::link('form kontak', '/kontak').' atau hitung perkiraan biayanya di '.self::link('halaman cek tarif', '/cek-tarif').'.'],
                ],
            ],
            [
                'title' => 'Asuransi Cargo: Lindungi Barang Berharga dari Kerusakan',
                'slug' => 'asuransi-cargo-lindungi-barang-berharga',
                'category' => 'tips-tutorial',
                'meta_title' => 'Asuransi Cargo untuk Barang Berharga | ATL Express',
                'meta_description' => 'Kapan Anda perlu asuransi cargo, bagaimana cara mengajukan klaim, dan tips pengemasan untuk mengurangi risiko kerusakan sebelum terjadi.',
                'days_ago' => 16,
                'hour' => 13,
                'lead' => 'Kerusakan pengiriman memang jarang terjadi, tetapi dampaknya besar ketika barang bernilai tinggi seperti elektronik, mesin, perhiasan, atau perlengkapan industri. Asuransi cargo membuat risiko ini punya penanganan yang jelas.',
                'sections' => [
                    ['Kapan Asuransi Justru Dibutuhkan',
                        'Asuransi layak dipertimbangkan saat nilai barang melebihi beberapa kali lipat ongkir, barang sulit diganti dengan cepat, atau pengiriman lintas pulau dengan banyak penanganan. Untuk barang murah yang mudah diganti, cadangan dana sendiri biasanya cukup.'],
                    ['Bagaimana Cara Klaimnya',
                        'Jika terjadi kerusakan atau kehilangan, pengirim mengisi formulir klaim, menyertakan nomor resi, foto barang sebelum dan sesudah, serta invoice atau bukti nilai. Tim kami membantu proses verifikasi agar penyelesaian berjalan lebih cepat.'],
                    ['Kurangi Risiko Sebelum Terjadi',
                        'Pengemasan adalah lapisan pertahanan pertama. Bubble wrap, pelindung sudut, kardus ganda, dan label fragile mengurangi dampak benturan selama bongkar muat. Untuk cairan, gunakan kemasan kedap suara yang tidak mudah pecah.'],
                ],
                'tips_title' => 'Dokumen yang Perlu Disiapkan',
                'tips' => [
                    'Foto barang dan kemasan sebelum dikirim.',
                    'Simpan invoice atau bukti pembelian barang.',
                    'Catat nomor resi dan waktu barang diterima.',
                    'Laporkan kerusakan dalam 1x24 jam sejak barang diterima.',
                ],
                'ctas' => [
                    ['Tanyakan pilihan asuransi untuk kiriman Anda',
                        'Tim kami bisa menjelaskan opsi asuransi dan batas nilainya melalui '.self::link('halaman kontak', '/kontak').'.'],
                ],
            ],
            [
                'title' => 'Metode Pembayaran QRIS, Transfer, dan COD untuk UMKM',
                'slug' => 'metode-pembayaran-qris-transfer-dan-cod-untuk-umkm',
                'category' => 'berita',
                'meta_title' => 'Metode Pembayaran Cargo: QRIS, Transfer, dan COD | ATL Express',
                'meta_description' => 'Pilihan pembayaran ongkir cargo ATL Express: QRIS, transfer bank, dan COD untuk UMKM, beserta tips memilih metode pembayaran yang aman untuk pengiriman barang.',
                'days_ago' => 18,
                'hour' => 9,
                'lead' => 'Sistem pembayaran yang membingungkan sering jadi hambatan bagi pemilik usaha kecil. Karena itu, opsi pembayaran online dibuat semudah mungkin: beberapa metode yang umum dipakai di Indonesia, tanpa administrasi yang rumit.',
                'sections' => [
                    ['Pembayaran yang Tersedia',
                        'Anda dapat memilih QRIS, transfer ke rekening bank, atau pembayaran tunai saat barang diterima untuk layanan tertentu. Semua pembayaran tercatat pada sistem sehingga mudah direkap di akhir bulan tanpa rekonsiliasi manual.'],
                    ['Mana yang Paling Cocok untuk UMKM',
                        'QRIS dan transfer cocok untuk pengiriman rutin dengan invoice atau nota, sedangkan COD memudahkan pembeli yang lebih nyaman membayar saat barang tiba. Pilih metode yang selaras dengan cara Anda mengelola kas usaha.'],
                    ['Keamanan Transaksi',
                        'Simpan bukti transfer dan catatan nomor resi sebagai dokumen. Hindari memberikan data pembayaran pribadi di luar kanal resmi kami. Tim kami selalu mengonfirmasi nominal tagihan sebelum pembayaran dilakukan.'],
                ],
                'tips_title' => 'Tips Mencatat Pembayaran',
                'tips' => [
                    'Lakukan rekonsiliasi pembayaran mingguan agar selisih tidak menumpuk.',
                    'Catat nomor resi pada setiap bukti pembayaran.',
                    'Untuk pengiriman rutin, minta harga kontrak agar ongkir lebih pasti.',
                    'Simpan kanal komunikasi resmi CS agar konfirmasi mudahenetkan.',
                ],
                'ctas' => [
                    ['Tanyakan opsi pembayaran untuk kebutuhan usaha',
                        'Hubungi tim kami lewat '.self::link('halaman kontak', '/kontak').' dan jelaskan pola pengiriman rutin Anda.'],
                ],
            ],
            [
                'title' => 'Kemasan Anti Rusak untuk Barang Rapuh dan Elektronik',
                'slug' => 'kemasan-anti-rusak-untuk-barang-rapuh-dan-elektronik',
                'category' => 'tips-tutorial',
                'meta_title' => 'Panduan Kemasan Anti Rusak untuk Barang Rapuh | ATL Express',
                'meta_description' => 'Cara mengemas barang rapuh, elektronik, kaca, dan cairan agar aman selama pengiriman cargo: bubble wrap, pelindung sudut, kardus dobel, dan label fragile.',
                'days_ago' => 20,
                'hour' => 16,
                'lead' => 'Banyak kerusakan kargo bermula dari kemasan yang terlalu rapuh. Kardus biasa tanpa pengisi internal bisa penyakiti sendiri hanya karena satu benturan saat dipindah antar kendaraan.kemasan yang tepat akan sangat mengurangi risiko ini.',
                'sections' => [
                    ['Bahan Pengemas yang Perlu Disiapkan',
                        'Lapis barang dengan bubble wrap minimal dua lapis, lindungi sudut dengan pelindung sudut, gunakan kardus dobel dengan kotak di dalam kotak, dan isi ruang kosong dengan busa atau kertas koran agar barang tidak bergeser. Untuk cairan, gunakan botol kedap suara yang diberi pouch pelindung.'],
                    ['Label dan Identitas yang Membantu Petugas',
                        'Tempelkan label alamat lengkap di beberapa sisi kemasan, bukan hanya di bagian atas. Tambahkan penanda FRAGILE atau HANDLE WITH CARE untuk barang yang mudah pecah agar penanganan di gudang lebih ekstra hati-hati.'],
                    ['Proses Pengemasan di ATL Express',
                        'Untuk pelanggan yang membutuhkan bantuan pengemasan, tim kami menyediakan opsi packing dengan bahan standar produksi. Pengemasan dilakukan di ruang packing terlindung dari panas dan hujan, bukan di bawah terik matahari, sehingga hasil lebih konsisten.'],
                ],
                'tips_title' => 'Checklist Pengemasan Aman',
                'tips' => [
                    'Uji kesesuaian kemasan dengan menggetuk isi kardus: barang tidak boleh bergerak di dalam box.',
                    'Tutup kardus dengan selotape yang menempel baik di kelima sisi, bukan hanya satu lapis.',
                    'Kirimkan foto kemasan lewat WhatsApp bila perlu peninjauan sebelum barang dikirim.',
                    'Konsultasikan kebutuhan bubble wrap melalui '.self::link('halaman kontak', '/kontak').'.',
                ],
                'ctas' => [
                    ['Butuh bantuan pengemasan?',
                        'Sampaikan detail barang Anda ke '.self::link('tim kami', '/kontak').' agar bahan packing yang disiapkan sesuai karakteristik produk.'],
                ],
            ],
            [
                'title' => 'ATL Express untuk Penjualan Marketplace dan UMKM Digital',
                'slug' => 'atl-express-untuk-penjualan-marketplace-dan-umkm-digital',
                'category' => 'kabar-perusahaan',
                'meta_title' => 'Jasa Kirim untuk Marketplace dan UMKM Digital | ATL Express',
                'meta_description' => 'Solusi logistik untuk penjual marketplace dan UMKM digital: kirim dari banyak lokasi, tracking real-time, ongkir transparan, dan tanpa minimum volume besar.',
                'days_ago' => 22,
                'hour' => 11,
                'lead' => 'Menjual online berarti menghadapi pertanyaan yang sama setiap hari: ongkir ke mana, barang saya sudah dikirim belum, dan kenapa belum sampai. Sistem pengiriman yang rapi membuat semua pertanyaan itu jauh lebih mudah ditangani.',
                'sections' => [
                    ['Pengiriman dari Banyak Lokasi',
                        'UMKM sering punya produk yang tersebar: sebagian di gudang, sebagian di rumah, sebagian di Mitra produksi. Layanan door-to-door memungkinkan barang dikirim dari lokasi mana pun tanpa perlu dikonsolidasikan lebih dulu di satu tempat.'],
                    ['Tarif yang Mudah Dipakai untuk Kalkulasi Margin',
                        'Dengan ongkir yang bisa dihitung online, Anda bisa memperkirakan margin per produk sebelum menentukan harga jual. Perubahan biaya dapat langsung diselaraskan tanpa menunggu penawaran tertulis dari agen.'],
                    ['Pengalaman Pelanggan yang Terlihat',
                        'Nomor resi yang bisa dilacak sendiri mengurangi pertanyaan dari pembeli, dan status yang transparan membangun kepercayaan. Untuk pengiriman yang sering, Anda dapat meminta solusi label dengan logo toko pada setiap kiriman.'],
                ],
                'tips_title' => 'Alur Kerja yang Disarankan',
                'tips' => [
                    'Tetapkan satu kontak operasional untuk semua pengiriman.',
                    'Gunakan template alamat yang sama untuk mempercepat proses penjemputan.',
                    'Pantau antrean pengiriman lewat '.self::link('cek resi', '/cek-resi').' setiap pagi.',
                    'Evaluasi biaya ongkir per produk setiap bulan agar margin tetap sehat.',
                ],
                'ctas' => [
                    ['Diskusikan kebutuhan toko Anda',
                        'Ceritakan pola pengiriman Anda melalui '.self::link('form kontak', '/kontak').' dan dapatkan penawaran yang sesuai.'],
                ],
            ],
            [
                'title' => 'Alasan ATL Express Jadi Pilihan Pengirim di Seluruh Indonesia',
                'slug' => 'alasan-atl-express-jadi-pilihan-pengirim-di-seluruh-indonesia',
                'category' => 'berita',
                'meta_title' => 'Mengapa ATL Express Jadi Pilihan Pengirim di Indonesia',
                'meta_description' => 'Alasan ATL Express dipercaya pengirim di seluruh Indonesia: tarif jelas, tracking real-time, jaringan luas, layanan pelanggan responsif, dan penanganan barang yang baik.',
                'days_ago' => 24,
                'hour' => 10,
                'lead' => 'Kepercayaan dibangun dari konsistensi, bukan dari satu momen yang baik. Berikut hal-hal yang menjadi standar kerja kami dalam menangani setiap kiriman dari ujung ke ujung Indonesia.',
                'sections' => [
                    ['Tarif yang Bisa Diprediksi',
                        'Pelanggan kami memperoleh estimasi ongkir sebelum barang diserahkan, sehingga tidak ada kejutan biaya di akhir perjalanan.'],
                    ['Tracking yang Membantu, Bukan Sekadar Formalitas',
                        'Nomor resi memberikan informasi yang bisa ditindaklanjuti, dan tim kami bekerja cepat bila status kiriman perlu ditelusuri lebih dalam.'],
                    ['Jaringan ke Seluruh Indonesia',
                        'Mitra dan jaringan distribusi kami menjangkau kota-kota besar maupun daerah di luar Jawa, termasuk wilayah timur dengan jarak tempuh yang jauh.'],
                    ['Tim yang Menjawab dengan Cepat',
                        'Pertanyaan tentang jadwal, tarif, atau dokumen dijawab melalui kanal WhatsApp dan email, termasuk pada hari kerja di luar jam kantor.'],
                    ['Penanganan Barang yang Diperhatikan',
                        'Proses sortir, pengemasan, dan bongkar muat mengikuti prosedur yang sama di setiap titik, sehingga kualitas penanganan tidak bergantung pada lokasi.'],
                ],
                'tips_title' => 'Apa yang Bisa Anda Harapkan',
                'tips' => [
                    'Pembaruan status tanpa perlu menanyakan berulang kali ke CS.',
                    'Penanganan klaim yang jelas bila terjadi masalah di lapangan.',
                    'Pilihan moda pengiriman yang disesuaikan dengan kebutuhan kiriman.',
                    'Komunikasi proaktif ketika ada rencana yang berubah.',
                ],
                'ctas' => [
                    ['Rasakan langsung layanannya',
                        'Mulai dengan mengirim paket pertama Anda lewat '.self::link('sistem pemesanan online', '/cek-tarif').' dan hubungi kami bila ada pertanyaan.'],
                ],
            ],
            [
                'title' => 'Ongkir Transparan: Bebas Biaya Tersembunyi Saat Kirim',
                'slug' => 'ongkir-transparan-tanpa-biaya-tersembunyi',
                'category' => 'tips-tutorial',
                'meta_title' => 'Ongkir Cargo Transparan Tanpa Biaya Tersembunyi',
                'meta_description' => 'Cara membaca rincian ongkir cargo: biaya dasar, berat volumetrik, minimum charge, area remote, dan biaya tambahan. Tips agar tidak kaget saat barang dikirim.',
                'days_ago' => 26,
                'hour' => 14,
                'lead' => 'Kaget saat menerima tagihan ongkir sering terjadi karena rincian biaya tidak dibahas sejak awal. Faktanya, sebagian besar selisih ongkir muncul dari hal-hal sederhana yang sebenarnya bisa dihindari.',
                'sections' => [
                    ['Komponen Biaya yang Perlu Dipahami',
                        'Biaya dasar dihitung dari berat atau volume, tergantung mana yang lebih besar. Selain itu ada minimum charge untuk kiriman kecil, biaya tambahan untuk area remote, serta biaya layanan tambahan seperti pengemasan dan asuransi.'],
                    ['Mengapa Barang Kecil Terasa Lebih Mahal per Kilogramnya',
                        'Ruang di kendaraan sudah terpakai, dan muatan kecil dengan volume besar membuat proses pengiriman tidak efisien. Karena itu, menggabungkan beberapa barang dalam satu paket sering menghasilkan ongkir per kilogram yang jauh lebih masuk akal.'],
                    ['Cara Menghindari Selisih di Akhir',
                        'Sampaikan dimensi paket dengan akurat sejak awal, konfirmasi komponen biaya sebelum menyetujui, dan simpan penawaran sebagai acuan. Tim kami di '.self::link('halaman kontak', '/kontak').' siap membantu memverifikasi rincian sebelum pengiriman.'],
                ],
                'tips_title' => 'Tips Hitung Ongkir Sendiri',
                'tips' => [
                    'Hitung volume dengan rumus panjang x lebar x tinggi dalam sentimeter.',
                    'Bandingkan berat aktual dan berat volumetrik, lalu ambil yang lebih besar.',
                    'Menggabungkan beberapa produk jadi satu paket sering menghemat ongkir.',
                    'Simpan tangkapan layar penawaran agar mudah dibandingkan.',
                ],
                'ctas' => [
                    ['Dapatkan rincian biaya yang jelas',
                        'Gunakan '.self::link('kalkulator cek tarif', '/cek-tarif').' untuk melihat estimasi ongkir sebelum barang diserahkan.'],
                ],
            ],
        ]);
    }
}
